'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CLPServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://customerpoints.clp.com/", ConfigurationName:="CLPServiceReference.CustomerPointsMgmt")>  _
    Public Interface CustomerPointsMgmt
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://customerpoints.clp.com/CustomerPointsMgmt/getBillDetailsRequest", ReplyAction:="http://customerpoints.clp.com/CustomerPointsMgmt/getBillDetailsResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(cancelTransaction)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getBillDetails)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getCustomerPoints))>  _
        Function getBillDetails(ByVal request As CLPServiceReference.getBillDetailsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> CLPServiceReference.getBillDetailsResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://customerpoints.clp.com/CustomerPointsMgmt/getCustomerPointsRequest", ReplyAction:="http://customerpoints.clp.com/CustomerPointsMgmt/getCustomerPointsResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(cancelTransaction)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getBillDetails)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getCustomerPoints))>  _
        Function getCustomerPoints(ByVal request As CLPServiceReference.getCustomerPointsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> CLPServiceReference.getCustomerPointsResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://customerpoints.clp.com/CustomerPointsMgmt/cancelTransactionRequest", ReplyAction:="http://customerpoints.clp.com/CustomerPointsMgmt/cancelTransactionResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(cancelTransaction)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getBillDetails)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(getCustomerPoints))>  _
        Function cancelTransaction(ByVal request As CLPServiceReference.cancelTransactionRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> CLPServiceReference.cancelTransactionResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://customerpoints.clp.com/")>  _
    Partial Public Class cancelTransaction
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private applicationIdField As String
        
        Private billnumberField As String
        
        Private billdateField As String
        
        Private card_noField As String
        
        Private outletField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property applicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
                Me.RaisePropertyChanged("applicationId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property billnumber() As String
            Get
                Return Me.billnumberField
            End Get
            Set
                Me.billnumberField = value
                Me.RaisePropertyChanged("billnumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property billdate() As String
            Get
                Return Me.billdateField
            End Get
            Set
                Me.billdateField = value
                Me.RaisePropertyChanged("billdate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property card_no() As String
            Get
                Return Me.card_noField
            End Get
            Set
                Me.card_noField = value
                Me.RaisePropertyChanged("card_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property outlet() As String
            Get
                Return Me.outletField
            End Get
            Set
                Me.outletField = value
                Me.RaisePropertyChanged("outlet")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://customerpoints.clp.com/")>  _
    Partial Public Class getBillDetails
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private applicationIdField As String
        
        Private billnumberField As String
        
        Private billdateField As Date
        
        Private billdateFieldSpecified As Boolean
        
        Private card_noField As String
        
        Private propertyField As String
        
        Private outletField As String
        
        Private billamtbeftaxField As Double
        
        Private billamtbeftaxFieldSpecified As Boolean
        
        Private billamtafttaxField As Double
        
        Private billamtafttaxFieldSpecified As Boolean
        
        Private billdetailsField() As String
        
        Private redemptionpointsField As Double
        
        Private redemptionpointsFieldSpecified As Boolean
        
        Private redemptiontypeField As String
        
        Private giftvouchertypeField As String
        
        Private workstationidField As String
        
        Private pointscalcField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property applicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
                Me.RaisePropertyChanged("applicationId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property billnumber() As String
            Get
                Return Me.billnumberField
            End Get
            Set
                Me.billnumberField = value
                Me.RaisePropertyChanged("billnumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property billdate() As Date
            Get
                Return Me.billdateField
            End Get
            Set
                Me.billdateField = value
                Me.RaisePropertyChanged("billdate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property billdateSpecified() As Boolean
            Get
                Return Me.billdateFieldSpecified
            End Get
            Set
                Me.billdateFieldSpecified = value
                Me.RaisePropertyChanged("billdateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property card_no() As String
            Get
                Return Me.card_noField
            End Get
            Set
                Me.card_noField = value
                Me.RaisePropertyChanged("card_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property [property]() As String
            Get
                Return Me.propertyField
            End Get
            Set
                Me.propertyField = value
                Me.RaisePropertyChanged("property")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property outlet() As String
            Get
                Return Me.outletField
            End Get
            Set
                Me.outletField = value
                Me.RaisePropertyChanged("outlet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property billamtbeftax() As Double
            Get
                Return Me.billamtbeftaxField
            End Get
            Set
                Me.billamtbeftaxField = value
                Me.RaisePropertyChanged("billamtbeftax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property billamtbeftaxSpecified() As Boolean
            Get
                Return Me.billamtbeftaxFieldSpecified
            End Get
            Set
                Me.billamtbeftaxFieldSpecified = value
                Me.RaisePropertyChanged("billamtbeftaxSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property billamtafttax() As Double
            Get
                Return Me.billamtafttaxField
            End Get
            Set
                Me.billamtafttaxField = value
                Me.RaisePropertyChanged("billamtafttax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property billamtafttaxSpecified() As Boolean
            Get
                Return Me.billamtafttaxFieldSpecified
            End Get
            Set
                Me.billamtafttaxFieldSpecified = value
                Me.RaisePropertyChanged("billamtafttaxSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("billdetails", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property billdetails() As String()
            Get
                Return Me.billdetailsField
            End Get
            Set
                Me.billdetailsField = value
                Me.RaisePropertyChanged("billdetails")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property redemptionpoints() As Double
            Get
                Return Me.redemptionpointsField
            End Get
            Set
                Me.redemptionpointsField = value
                Me.RaisePropertyChanged("redemptionpoints")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property redemptionpointsSpecified() As Boolean
            Get
                Return Me.redemptionpointsFieldSpecified
            End Get
            Set
                Me.redemptionpointsFieldSpecified = value
                Me.RaisePropertyChanged("redemptionpointsSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property redemptiontype() As String
            Get
                Return Me.redemptiontypeField
            End Get
            Set
                Me.redemptiontypeField = value
                Me.RaisePropertyChanged("redemptiontype")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property giftvouchertype() As String
            Get
                Return Me.giftvouchertypeField
            End Get
            Set
                Me.giftvouchertypeField = value
                Me.RaisePropertyChanged("giftvouchertype")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property workstationid() As String
            Get
                Return Me.workstationidField
            End Get
            Set
                Me.workstationidField = value
                Me.RaisePropertyChanged("workstationid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property pointscalc() As Boolean
            Get
                Return Me.pointscalcField
            End Get
            Set
                Me.pointscalcField = value
                Me.RaisePropertyChanged("pointscalc")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://customerpoints.clp.com/")>  _
    Partial Public Class getCustomerPoints
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private applicationIdField As String
        
        Private cardNoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property applicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
                Me.RaisePropertyChanged("applicationId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cardNo() As String
            Get
                Return Me.cardNoField
            End Get
            Set
                Me.cardNoField = value
                Me.RaisePropertyChanged("cardNo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getBillDetails", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class getBillDetailsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public applicationId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billnumber As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billdate As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public card_no As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [property] As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=5),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public outlet As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=6),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billamtbeftax As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=7),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billamtafttax As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=8),  _
         System.Xml.Serialization.XmlElementAttribute("billdetails", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public billdetails() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=9),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public redemptionpoints As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=10),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public redemptiontype As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=11),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public giftvouchertype As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=12),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public workstationid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=13),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pointscalc As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal applicationId As String, ByVal billnumber As String, ByVal billdate As Date, ByVal card_no As String, ByVal [property] As String, ByVal outlet As String, ByVal billamtbeftax As Double, ByVal billamtafttax As Double, ByVal billdetails() As String, ByVal redemptionpoints As Double, ByVal redemptiontype As String, ByVal giftvouchertype As String, ByVal workstationid As String, ByVal pointscalc As Boolean)
            MyBase.New
            Me.applicationId = applicationId
            Me.billnumber = billnumber
            Me.billdate = billdate
            Me.card_no = card_no
            Me.[property] = [property]
            Me.outlet = outlet
            Me.billamtbeftax = billamtbeftax
            Me.billamtafttax = billamtafttax
            Me.billdetails = billdetails
            Me.redemptionpoints = redemptionpoints
            Me.redemptiontype = redemptiontype
            Me.giftvouchertype = giftvouchertype
            Me.workstationid = workstationid
            Me.pointscalc = pointscalc
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getBillDetailsResponse", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class getBillDetailsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return]() As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As Object)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCustomerPoints", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class getCustomerPointsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public applicationId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public cardNo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal applicationId As String, ByVal cardNo As String)
            MyBase.New
            Me.applicationId = applicationId
            Me.cardNo = cardNo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCustomerPointsResponse", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class getCustomerPointsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return]() As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As Object)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cancelTransaction", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class cancelTransactionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public applicationId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billnumber As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billdate As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public card_no As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public outlet As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal applicationId As String, ByVal billnumber As String, ByVal billdate As String, ByVal card_no As String, ByVal outlet As String)
            MyBase.New
            Me.applicationId = applicationId
            Me.billnumber = billnumber
            Me.billdate = billdate
            Me.card_no = card_no
            Me.outlet = outlet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cancelTransactionResponse", WrapperNamespace:="http://customerpoints.clp.com/", IsWrapped:=true)>  _
    Partial Public Class cancelTransactionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://customerpoints.clp.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return]() As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As Object)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CustomerPointsMgmtChannel
        Inherits CLPServiceReference.CustomerPointsMgmt, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CustomerPointsMgmtClient
        Inherits System.ServiceModel.ClientBase(Of CLPServiceReference.CustomerPointsMgmt)
        Implements CLPServiceReference.CustomerPointsMgmt
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CLPServiceReference_CustomerPointsMgmt_getBillDetails(ByVal request As CLPServiceReference.getBillDetailsRequest) As CLPServiceReference.getBillDetailsResponse Implements CLPServiceReference.CustomerPointsMgmt.getBillDetails
            Return MyBase.Channel.getBillDetails(request)
        End Function
        
        Public Function getBillDetails(ByVal applicationId As String, ByVal billnumber As String, ByVal billdate As Date, ByVal card_no As String, ByVal [property] As String, ByVal outlet As String, ByVal billamtbeftax As Double, ByVal billamtafttax As Double, ByVal billdetails() As String, ByVal redemptionpoints As Double, ByVal redemptiontype As String, ByVal giftvouchertype As String, ByVal workstationid As String, ByVal pointscalc As Boolean) As Object()
            Dim inValue As CLPServiceReference.getBillDetailsRequest = New CLPServiceReference.getBillDetailsRequest()
            inValue.applicationId = applicationId
            inValue.billnumber = billnumber
            inValue.billdate = billdate
            inValue.card_no = card_no
            inValue.[property] = [property]
            inValue.outlet = outlet
            inValue.billamtbeftax = billamtbeftax
            inValue.billamtafttax = billamtafttax
            inValue.billdetails = billdetails
            inValue.redemptionpoints = redemptionpoints
            inValue.redemptiontype = redemptiontype
            inValue.giftvouchertype = giftvouchertype
            inValue.workstationid = workstationid
            inValue.pointscalc = pointscalc
            Dim retVal As CLPServiceReference.getBillDetailsResponse = CType(Me,CLPServiceReference.CustomerPointsMgmt).getBillDetails(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CLPServiceReference_CustomerPointsMgmt_getCustomerPoints(ByVal request As CLPServiceReference.getCustomerPointsRequest) As CLPServiceReference.getCustomerPointsResponse Implements CLPServiceReference.CustomerPointsMgmt.getCustomerPoints
            Return MyBase.Channel.getCustomerPoints(request)
        End Function
        
        Public Function getCustomerPoints(ByVal applicationId As String, ByVal cardNo As String) As Object()
            Dim inValue As CLPServiceReference.getCustomerPointsRequest = New CLPServiceReference.getCustomerPointsRequest()
            inValue.applicationId = applicationId
            inValue.cardNo = cardNo
            Dim retVal As CLPServiceReference.getCustomerPointsResponse = CType(Me,CLPServiceReference.CustomerPointsMgmt).getCustomerPoints(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CLPServiceReference_CustomerPointsMgmt_cancelTransaction(ByVal request As CLPServiceReference.cancelTransactionRequest) As CLPServiceReference.cancelTransactionResponse Implements CLPServiceReference.CustomerPointsMgmt.cancelTransaction
            Return MyBase.Channel.cancelTransaction(request)
        End Function
        
        Public Function cancelTransaction(ByVal applicationId As String, ByVal billnumber As String, ByVal billdate As String, ByVal card_no As String, ByVal outlet As String) As Object()
            Dim inValue As CLPServiceReference.cancelTransactionRequest = New CLPServiceReference.cancelTransactionRequest()
            inValue.applicationId = applicationId
            inValue.billnumber = billnumber
            inValue.billdate = billdate
            inValue.card_no = card_no
            inValue.outlet = outlet
            Dim retVal As CLPServiceReference.cancelTransactionResponse = CType(Me,CLPServiceReference.CustomerPointsMgmt).cancelTransaction(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
