
Imports BL
Imports DevExpress.XtraGrid.Views.Grid
Imports CrystalDecisions.Shared
Imports CrystalDecisions.CrystalReports.Engine

Public Class CarBookingDetails

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Public FRMSTRING As String
    Public SALEREGID As Integer

    Private Sub CarBookingDetails_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.N And e.Alt = True Then
                showform(False, 0)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable
            If ClientName = "SCC" Then
                dt = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_REFNO AS REFNO, CARBOOKINGMASTER.BOOKING_DATE AS BOOKINGDATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, ISNULL(GUESTMASTER.GUEST_EMAIL, '') AS EMAIL, LEDGERS.Acc_cmpname AS ACCNAME, CARBOOKINGMASTER.BOOKING_PACKAGEFROM AS [FROM], CARBOOKINGMASTER.BOOKING_PACKAGETO AS [TO], CARBOOKINGMASTER.BOOKING_TOTALPURAMT AS PURTOTAL, CARBOOKINGMASTER.BOOKING_GRANDTOTAL AS GRANDTOTAL, USERMASTER.User_Name AS USERNAME, CARBOOKINGMASTER.BOOKING_SALERETURN AS [RETURN], CARBOOKINGMASTER.BOOKING_DISPUTE AS DISPUTED, CARBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, CARBOOKINGMASTER.BOOKING_BILLCHECKED AS BILLCHECKED, ISNULL(PURTAXMASTER.tax_name, '') AS PURTAXNAME, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXAMT, 0) AS PURTAXAMT, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(CARBOOKINGMASTER.BOOKING_TAX, 0) AS TAXAMT, CARBOOKINGMASTER.BOOKING_SUBTOTAL AS SUBTOTAL, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NETT AS PURSUBTOTAL, ISNULL(CARBOOKINGMASTER.BOOKING_CONFIRMEDBY, '') AS CONFIRMEDBY, ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0) AS STARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0) AS ENDKMS, ISNULL( BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE, (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0)) AS TOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0))-40 ELSE (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0)) END) END  AS EXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0) AS STARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0) AS ENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0)) AS TOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0))-4 ELSE (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0)) END) END  AS EXTRATIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0) AS PURSTARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0) AS PURENDKMS, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) AS PURTOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END  AS PUREXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0) AS PURSTARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0) AS PURENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) AS PURTOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END  AS PUREXTRATIME, ISNULL(DRIVERMASTER.DRIVER_NAME, '') AS DRIVERNAME, ISNULL(VEHICLEMASTER.VEHICLE_NAME, '') AS VEHICLENAME, ISNULL(CARBOOKINGMASTER_DESC.BOOKING_VEHICLENO, '') AS VEHICLENO, ISNULL(CARBOOKINGMASTER.BOOKING_OTHERCHGS,0) AS OTHERCHGS, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_OTHERCHGS,0) AS PUROTHERCHGS, ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day,CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO))+1 ELSE 0 END  AS DAYS, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day,CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO)) ELSE 0 END  AS NIGHTS,ISNULL(GROUPDEPARTURE.GROUPDEP_NAME, '') AS GROUPDEPARTURE ", "", "GROUPDEPARTURE LEFT OUTER JOIN CARBOOKINGMASTER INNER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id INNER JOIN GUESTMASTER ON CARBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID INNER JOIN CARBOOKINGMASTER_DESC ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_DESC.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN VEHICLEMASTER ON CARBOOKINGMASTER_DESC.BOOKING_VEHICLEID = VEHICLEMASTER.VEHICLE_ID ON GROUPDEPARTURE.GROUPDEP_NO = CARBOOKINGMASTER.BOOKING_GROUPDEPARTID LEFT OUTER JOIN DRIVERMASTER ON CARBOOKINGMASTER_DESC.BOOKING_DRIVERID = DRIVERMASTER.DRIVER_ID LEFT OUTER JOIN TAXMASTER ON CARBOOKINGMASTER.BOOKING_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id ", " AND CARBOOKINGMASTER.BOOKING_YEARID = " & YearId & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")
            Else
                ' dt = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_REFNO AS REFNO, CARBOOKINGMASTER.BOOKING_DATE AS BOOKINGDATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, ISNULL(GUESTMASTER.GUEST_EMAIL, '') AS EMAIL, LEDGERS.Acc_cmpname AS ACCNAME, CARBOOKINGMASTER.BOOKING_PACKAGEFROM AS [FROM], CARBOOKINGMASTER.BOOKING_PACKAGETO AS [TO], CARBOOKINGMASTER.BOOKING_TOTALPURAMT AS PURTOTAL, CARBOOKINGMASTER.BOOKING_GRANDTOTAL AS GRANDTOTAL, USERMASTER.User_Name AS USERNAME, CARBOOKINGMASTER.BOOKING_SALERETURN AS [RETURN], CARBOOKINGMASTER.BOOKING_DISPUTE AS DISPUTED, CARBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, CARBOOKINGMASTER.BOOKING_BILLCHECKED AS BILLCHECKED, ISNULL(PURTAXMASTER.tax_name, '') AS PURTAXNAME, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXAMT,0) AS PURTAXAMT, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(CARBOOKINGMASTER.BOOKING_TAX,0) AS TAXAMT, CARBOOKINGMASTER.BOOKING_SUBTOTAL AS SUBTOTAL, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NETT AS PURSUBTOTAL, ISNULL(BOOKING_CONFIRMEDBY,'') AS CONFIRMEDBY, ISNULL(BOOKING_STARTKMS,0) AS STARTKMS, ISNULL(BOOKING_ENDKMS,0) AS ENDKMS, ISNULL(BOOKING_PURSTARTKMS,0) AS PURSTARTKMS, ISNULL(BOOKING_PURENDKMS,0) AS PURENDKMS, ISNULL(CARBOOKINGMASTER.BOOKING_OTHERCHGS,0) AS OTHERCHGS, ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day,CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO))+1 ELSE 0 END  AS DAYS ", "", " GUESTMASTER RIGHT OUTER JOIN CARBOOKINGMASTER LEFT OUTER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id LEFT OUTER JOIN TAXMASTER ON CARBOOKINGMASTER.BOOKING_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO AND  CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id ON GUESTMASTER.GUEST_ID = CARBOOKINGMASTER.BOOKING_GUESTID  ", " AND CARBOOKINGMASTER.BOOKING_YEARID = " & YearId & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")
                dt = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_REFNO AS REFNO, CARBOOKINGMASTER.BOOKING_DATE AS BOOKINGDATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, ISNULL(GUESTMASTER.GUEST_EMAIL, '') AS EMAIL, LEDGERS.Acc_cmpname AS ACCNAME, CARBOOKINGMASTER.BOOKING_PACKAGEFROM AS [FROM], CARBOOKINGMASTER.BOOKING_PACKAGETO AS [TO], CARBOOKINGMASTER.BOOKING_TOTALPURAMT AS PURTOTAL, CARBOOKINGMASTER.BOOKING_GRANDTOTAL AS GRANDTOTAL, USERMASTER.User_Name AS USERNAME, CARBOOKINGMASTER.BOOKING_SALERETURN AS [RETURN], CARBOOKINGMASTER.BOOKING_DISPUTE AS DISPUTED, CARBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, CARBOOKINGMASTER.BOOKING_BILLCHECKED AS BILLCHECKED, ISNULL(PURTAXMASTER.tax_name, '') AS PURTAXNAME, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXAMT, 0) AS PURTAXAMT, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(CARBOOKINGMASTER.BOOKING_TAX, 0) AS TAXAMT, CARBOOKINGMASTER.BOOKING_SUBTOTAL AS SUBTOTAL, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NETT AS PURSUBTOTAL, ISNULL(CARBOOKINGMASTER.BOOKING_CONFIRMEDBY, '') AS CONFIRMEDBY, ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0) AS STARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0) AS ENDKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0) AS PURSTARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0) AS PURENDKMS, ISNULL(CARBOOKINGMASTER.BOOKING_OTHERCHGS, 0) AS OTHERCHGS, ISNULL(CARBOOKINGMASTER.BOOKING_TYPE, 'LOCAL') AS BOOKINGTYPE, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE, 'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day, CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO)) + 1 ELSE 0 END AS DAYS, ISNULL(STATEMASTER.state_name, '') AS STATENAME, ISNULL(LEDGERS.ACC_GSTIN, '') AS GSTIN, ISNULL(CARBOOKINGMASTER.BOOKING_TAXSERVCHGSAMT, 0) AS TAXSERVCHGSAMT, ISNULL(HSNMASTER.HSN_CODE, '') AS HSNCODE, ISNULL(CARBOOKINGMASTER.BOOKING_CGSTPER, 0) AS CGSTPER, ISNULL(CARBOOKINGMASTER.BOOKING_CGSTAMT, 0) AS CGSTAMT, ISNULL(CARBOOKINGMASTER.BOOKING_SGSTPER, 0) AS SGSTPER, ISNULL(CARBOOKINGMASTER.BOOKING_SGSTAMT, 0) AS SGSTAMT, ISNULL(CARBOOKINGMASTER.BOOKING_IGSTPER, 0) AS IGSTPER, ISNULL(CARBOOKINGMASTER.BOOKING_IGSTAMT, 0) AS IGSTAMT, ISNULL(CARBOOKINGMASTER.BOOKING_IRNNO, '') AS IRNNO, ISNULL(CARBOOKINGMASTER.BOOKING_ACKNO, '') AS ACKNO, CARBOOKINGMASTER.BOOKING_ACKDATE AS ACKDATE, CARBOOKINGMASTER.BOOKING_QRCODE AS QRCODE, ISNULL(GROUPDEPARTURE.GROUPDEP_NAME, '') AS GROUPDEPARTURE ", "", " TAXMASTER RIGHT OUTER JOIN CARBOOKINGMASTER LEFT OUTER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id LEFT OUTER JOIN GROUPDEPARTURE ON CARBOOKINGMASTER.BOOKING_GROUPDEPARTID = GROUPDEPARTURE.GROUPDEP_NO LEFT OUTER JOIN HSNMASTER ON CARBOOKINGMASTER.BOOKING_HSNCODEID = HSNMASTER.HSN_ID LEFT OUTER JOIN STATEMASTER ON LEDGERS.Acc_stateid = STATEMASTER.state_id ON TAXMASTER.tax_id = CARBOOKINGMASTER.BOOKING_TAXID LEFT OUTER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id LEFT OUTER JOIN GUESTMASTER ON CARBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID", " AND CARBOOKINGMASTER.BOOKING_YEARID = " & YearId & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")

                GDRIVERNAME.Visible = False
                GPURSTART.Visible = False
                GPUREND.Visible = False
                GPURSTARTTIME.Visible = False
                GPURENDTIME.Visible = False
                GPURTOTALKMS.Visible = False
                GPUREXTRAKMS.Visible = False
                GPURTOTALTIME.Visible = False
                GPUREXTRATIME.Visible = False
                GPUROTHERCHGS.Visible = False
            End If
            gridbilldetails.DataSource = dt
            If ClientName = "SCC" Then GREFNO.VisibleIndex = 28

            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub showform(ByVal editval As Boolean, ByVal BOOKINGNO As Integer)
        Try
            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If

            If (editval = False) Or (editval = True And gridbill.RowCount > 0) Then
                Dim OBJBOOKING As New CarBooking
                OBJBOOKING.MdiParent = MDIMain
                OBJBOOKING.edit = editval
                OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                OBJBOOKING.Show()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub ToolStripButton1_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles ToolStripButton1.Click
        Try
            If USERADD = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            showform(False, 0)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub CMDOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDOK.Click
        Try
            showform(True, gridbill.GetFocusedRowCellValue("BOOKINGNO"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles gridbill.DoubleClick
        Try
            showform(True, gridbill.GetFocusedRowCellValue("BOOKINGNO"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CarBookingDetails_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow = USERRIGHTS.Select("FormName = 'CAR RENTAL'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If ClientName = "ARUN" Or ClientName = "SCC" Then GREFNO.Caption = "Night Allowance"

            Dim clscommon As New ClsCommon
            Dim dt As DataTable = clscommon.search(" register_abbr, register_initials, register_id ", "", " RegisterMaster ", " and register_name ='VEHICLE SALE REGISTER' and register_type = 'SALE' and register_YEARid = " & YearId)
            If dt.Rows.Count > 0 Then SALEREGID = dt.Rows(0).Item(2)


            fillgrid()


        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            Dim DT As DataTable = gridbilldetails.DataSource
            If gridbill.RowFilter = "" Then
                If e.RowHandle >= 0 Then
                    Dim ROW As DataRow = DT.Rows(e.RowHandle)
                    Dim View As GridView = sender
                    If Val(View.GetRowCellDisplayText(e.RowHandle, View.Columns("RETURN"))) > 0 Then
                        e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Regular)
                        e.Appearance.BackColor = Color.Yellow

                    ElseIf View.GetRowCellDisplayText(e.RowHandle, View.Columns("BILLCHECKED")) = "Checked" Then
                        e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Regular)
                        e.Appearance.BackColor = Color.LightGreen

                    ElseIf View.GetRowCellDisplayText(e.RowHandle, View.Columns("DISPUTED")) = "Checked" Then
                        e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Regular)
                        e.Appearance.BackColor = Color.LightBlue
                    End If
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub ExcelExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ExcelExport.Click
        Try
            Dim PATH As String = ""
            PATH = Application.StartupPath & "\Car Booking Details.XLS"
            If FileIO.FileSystem.FileExists(PATH) = True Then FileIO.FileSystem.DeleteFile(PATH)

            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True

            Dim workbook As String = PATH
            If FileIO.FileSystem.FileExists(PATH) = True Then Interaction.GetObject(workbook).close(False)
            GC.Collect()
            'For Each proc In System.Diagnostics.Process.GetProcessesByName("Excel")
            '    proc.Kill()
            'Next

            Dim PERIOD As String = ""
            PERIOD = AccFrom & " - " & AccTo

            opti.SheetName = "Car Booking Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Car Booking Details", gridbill.VisibleColumns.Count + gridbill.GroupCount, "", PERIOD)

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CarBookingDetails_Shown(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Shown
        If ClientName = "CLASSIC" And ClientName = "TOPCOMM" And ClientName = "AMIGO" And ClientName = "PARAMOUNT" Then Me.Close()
        If ClientName = "SEASONED" Then
            PRINTTOOL.Visible = True
            LBLFROM.Visible = True
            LBLTO.Visible = True
            TXTFROM.Visible = True
            TXTTO.Visible = True
        End If
        If ClientName = "GLOBAL" Then
            GSTATE.Visible = False
            GGSTIN.Visible = False
            GCGSTPER.Visible = False
            gCGSTAMT.Visible = False
            gSGSTPER.Visible = False
            gSGSTAMT.Visible = False
            gIGSTPER.Visible = False
            gIGSTAMT.Visible = False
            gHSNCODE.Visible = False

        End If
    End Sub

    Private Sub TOOLMAIL_Click(sender As Object, e As EventArgs) Handles TOOLMAIL.Click
        Try
            If (Val(TXTFROM.Text.Trim) = 0 Or Val(TXTTO.Text.Trim) = 0 Or Val(TXTCOPIES.Text.Trim) = 0) AndAlso gridbill.SelectedRowsCount = 0 Then Exit Sub
            'IF WE HAVE SELECTED FROM AND TO THEN WORK WITH THE CURRENT CODE ELSE GO FOR SELECTED ENTRIES CODE
            If Val(TXTFROM.Text.Trim) > 0 And Val(TXTTO.Text.Trim) > 0 Then
                If Val(TXTFROM.Text.Trim) > Val(TXTTO.Text.Trim) Then
                    MsgBox("Enter Propoer Invoice Nos", MsgBoxStyle.Critical)
                    Exit Sub
                Else
                    If MsgBox("Wish to Mail Invoice from " & Val(TXTFROM.Text.Trim) & " To " & Val(TXTTO.Text.Trim) & " ?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
                    serverprop(True)
                End If
            Else
                If MsgBox("Wish to Mail Selected Invoice ?", MsgBoxStyle.YesNo) = vbYes Then SERVERPROPSELECTED(True)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub TOOLREFRESH_Click(sender As Object, e As EventArgs) Handles TOOLREFRESH.Click
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    'Private Sub TOOLGRIDDETAILS_Click(sender As Object, e As EventArgs) Handles TOOLGRIDDETAILS.Click
    '    Try
    '        Dim OBJGRID As New CarbookingGridDetails
    '        OBJGRID.MdiParent = MDIMain
    '        OBJGRID.FRMSTRING = FRMSTRING
    '        OBJGRID.Show()
    '    Catch ex As Exception
    '        Throw ex
    '    End Try
    'End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PRINTTOOL.Click
        Try
            If (Val(TXTFROM.Text.Trim) = 0 Or Val(TXTTO.Text.Trim) = 0 Or Val(TXTCOPIES.Text.Trim) = 0) AndAlso gridbill.SelectedRowsCount = 0 Then Exit Sub
            'IF WE HAVE SELECTED FROM AND TO THEN WORK WITH THE CURRENT CODE ELSE GO FOR SELECTED ENTRIES CODE
            If Val(TXTFROM.Text.Trim) > 0 And Val(TXTTO.Text.Trim) > 0 Then
                If Val(TXTFROM.Text.Trim) > Val(TXTTO.Text.Trim) Then
                    MsgBox("Enter Propoer Invoice Nos", MsgBoxStyle.Critical)
                    Exit Sub
                Else
                    If MsgBox("Wish to Print Invoice from " & Val(TXTFROM.Text.Trim) & " To " & Val(TXTTO.Text.Trim) & " ?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
                    serverprop(False)
                End If
            Else
                If MsgBox("Wish to Print Selected Invoice ?", MsgBoxStyle.YesNo) = vbYes Then SERVERPROPSELECTED(False)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub serverprop(Optional ByVal INVOICEMAIL As Boolean = False)
        Try
            'For I As Integer = Val(TXTFROM.Text.Trim) To Val(TXTTO.Text.Trim)
            '    Dim OBJINVOICE As New CarBookingVoucherDesign
            '    OBJINVOICE.MdiParent = MDIMain
            '    OBJINVOICE.DIRECTPRINT = True
            '    OBJINVOICE.FRMSTRING = "INVOICE"
            '    OBJINVOICE.BOOKINGNO = Val(I)
            '    OBJINVOICE.SALEREGISTERID = SALEREGID
            '    OBJINVOICE.Show()
            '    OBJINVOICE.Close()
            'Next
            Dim ALATTACHMENT As New ArrayList
            If INVOICEMAIL = False Then If PRINTDIALOG.ShowDialog = DialogResult.OK Then PRINTDOC.PrinterSettings = PRINTDIALOG.PrinterSettings
            For I As Integer = Val(TXTFROM.Text.Trim) To Val(TXTTO.Text.Trim)
                Dim OBJINVOICE As New CarBookingVoucherDesign
                OBJINVOICE.MdiParent = MDIMain
                OBJINVOICE.DIRECTPRINT = True
                OBJINVOICE.FRMSTRING = "INVOICE"
                OBJINVOICE.DIRECTMAIL = INVOICEMAIL
                OBJINVOICE.BOOKINGNO = Val(I)
                OBJINVOICE.SALEREGISTERID = SALEREGID
                OBJINVOICE.PRINTSETTING = PRINTDIALOG
                OBJINVOICE.NOOFCOPIES = Val(TXTCOPIES.Text.Trim)
                OBJINVOICE.Show()
                OBJINVOICE.Close()
                ALATTACHMENT.Add(Application.StartupPath & "\INVOICE_" & I & ".pdf")
            Next

            If INVOICEMAIL Then
                Dim OBJMAIL As New SendMail
                OBJMAIL.ALATTACHMENT = ALATTACHMENT
                OBJMAIL.subject = "Invoice"
                OBJMAIL.ShowDialog()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SERVERPROPSELECTED(Optional ByVal INVOICEMAIL As Boolean = False)
        Try

            Dim ALATTACHMENT As New ArrayList

            If INVOICEMAIL = False Then If PRINTDIALOG.ShowDialog = DialogResult.OK Then PRINTDOC.PrinterSettings = PRINTDIALOG.PrinterSettings
            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim ROW As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))

                Dim OBJINVOICE As New CarBookingVoucherDesign
                OBJINVOICE.MdiParent = MDIMain
                OBJINVOICE.DIRECTPRINT = True
                OBJINVOICE.FRMSTRING = "INVOICE"
                OBJINVOICE.DIRECTMAIL = INVOICEMAIL
                OBJINVOICE.BOOKINGNO = Val(ROW("BOOKINGNO"))
                OBJINVOICE.BOOKINGDATE = ROW("BOOKINGDATE")
                OBJINVOICE.SALEREGISTERID = SALEREGID
                OBJINVOICE.PRINTSETTING = PRINTDIALOG
                OBJINVOICE.NOOFCOPIES = Val(TXTCOPIES.Text.Trim)
                OBJINVOICE.Show()
                OBJINVOICE.Close()
                ALATTACHMENT.Add(Application.StartupPath & "\INVOICE_" & Val(ROW("BOOKINGNO")) & ".pdf")
            Next

            If INVOICEMAIL Then
                Dim OBJMAIL As New SendMail
                OBJMAIL.ALATTACHMENT = ALATTACHMENT
                OBJMAIL.subject = "Invoice"
                OBJMAIL.ShowDialog()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class