
Imports BL

Public Class HomePage

    Private Sub acc_cmd_Click() Handles ACC_CMD.Click
        Try
            Dim objacc As New AccountsDetails
            objacc.frmstring = "ACCOUNTS"
            objacc.MdiParent = MDIMain
            objacc.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub HOTEL_CMD_Click() Handles HOTEL_CMD.Click
        Try
            Dim OBJHOTEL As New HotelDetails
            OBJHOTEL.MdiParent = MDIMain
            OBJHOTEL.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PAYMENT_CMD_Click() Handles PAYMENT_CMD.Click
        Try
            Dim objpay As New PaymentMaster
            objpay.MdiParent = MDIMain
            objpay.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub RECEIPT_CMD_Click() Handles RECEIPT_CMD.Click
        Try
            Dim objrec As New Receipt
            objrec.MdiParent = MDIMain
            objrec.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CONTRA_CMD_Click() Handles CONTRA_CMD.Click
        Try
            Dim objcontra As New ContraEntry
            objcontra.MdiParent = MDIMain
            objcontra.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub BANK_CMD_Click() Handles BANK_CMD.Click
        Try
            Dim objbank As New BankRegister
            objbank.MdiParent = MDIMain
            objbank.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub LEDGER_CMD_Click() Handles LEDGER_CMD.Click
        Try
            Dim objledger As New LedgerBook
            objledger.MdiParent = MDIMain
            objledger.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub JOURNAL_CMD_Click() Handles JOURNAL_CMD.Click
        Try
            Dim objjv As New journal
            objjv.MdiParent = MDIMain
            objjv.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub Label1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles lblacccentre.Click
        Call acc_cmd_Click()
    End Sub

    Private Sub HOTELBOOKING_CMD_Click() Handles HOTELBOOKING_CMD.Click
        Try
            Dim OBJBOOKING As New HotelBookings
            OBJBOOKING.FRMSTRING = "BOOKING"
            OBJBOOKING.MdiParent = MDIMain
            OBJBOOKING.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub Label1_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label1.Click
        Call HOTEL_CMD_Click()
    End Sub

    Private Sub Label3_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label3.Click
        Call HOTELBOOKING_CMD_Click()
    End Sub

    Private Sub Label8_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label8.Click
        Call PAYMENT_CMD_Click()
    End Sub

    Private Sub Label7_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label7.Click
        Call RECEIPT_CMD_Click()
    End Sub

    Private Sub Label13_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label13.Click
        Call CONTRA_CMD_Click()
    End Sub

    Private Sub Label9_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label9.Click
        Call BANK_CMD_Click()
    End Sub

    Private Sub Label10_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label10.Click
        Call LEDGER_CMD_Click()
    End Sub

    Private Sub Label12_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label12.Click
        Call VOUCHER_CMD_Click()
    End Sub

    Private Sub VOUCHER_CMD_Click() Handles VOUCHER_CMD.Click
        Try
            Dim OBJNP As New ExpenseVoucher
            OBJNP.FRMSTRING = "NONPURCHASE"
            OBJNP.MdiParent = MDIMain
            OBJNP.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub Label11_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label11.Click
        Call JOURNAL_CMD_Click()
    End Sub

    Private Sub HomePage_Activated(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Activated
        Try
            Me.Refresh()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub AIRLINEBOOKING_CMD_Click() Handles AIRLINEBOOKING_CMD.Click
        Try
            Dim OBJBOOKING As New AirlineBookings
            OBJBOOKING.MdiParent = MDIMain
            OBJBOOKING.FRMSTRING = "DOMESTIC"
            OBJBOOKING.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub Label4_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label4.Click
        Call AIRLINEBOOKING_CMD_Click()
    End Sub

    Private Sub FLIGHT_CMD_Click() Handles FLIGHT_CMD.Click
        Try
            Dim OBJFLIGHT As New FlightDetails
            OBJFLIGHT.MdiParent = MDIMain
            OBJFLIGHT.Show()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub Label2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Label2.Click
        Call FLIGHT_CMD_Click()
    End Sub

    Private Sub HomePage_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        'Try
        '    LBLCHECKIN.Left = Me.Width
        '    Dim WHERECLAUSE As String = " AND BOOKING_ARRIVAL = '" & Format(DateAdd(DateInterval.Day, 1, Mydate), "MM/dd/yyyy") & "'"
        '    If UserName <> "Admin" Then WHERECLAUSE = " AND BOOKEDBYMASTER.BOOKEDBY_NAME = ' " & UserName & "'"

        '    Dim CHECKINNAMES As String = "There is No Check In for Tomorrow."
        '    Dim objclsCMST As New ClsCommonMaster
        '    Dim dt As DataTable = objclsCMST.search("  HOTELBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS [DATE], GUESTMASTER.GUEST_NAME AS GUESTNAME , HOTELMASTER.HOTEL_NAME AS HOTELNAME,  HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME aS BOOKEDBY, BOOKING_SALEBALANCE AS BALANCE, BOOKING_BOOKTYPE AS TYPE ", "", " HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID ", WHERECLAUSE & " AND BOOKING_CANCELLED = 'FALSE' AND BOOKING_CMPID =" & CmpId & " AND BOOKING_LOCATIONID = " & Locationid & " AND BOOKING_YEARID = " & YearId)
        '    If dt.Rows.Count > 0 Then
        '        CHECKINNAMES = ""
        '        For Each ROW As DataRow In dt.Rows
        '            CHECKINNAMES = CHECKINNAMES & ROW("BOOKINGNO") & " - " & ROW("GUESTNAME") & " - " & ROW("HOTELNAME") & "                        "
        '        Next
        '    End If
        '    LBLCHECKIN.Text = CHECKINNAMES

        'Catch ex As Exception
        '    Throw ex
        'End Try
        Try
            If OUTSTANDING = True Or UserName = "Admin" Then
                PANELOUTSTANDING.Visible = True
                FILLPAYGRID("")
                FILLRECGRID("")
            End If

            If CHECKIN = True Or UserName = "Admin" Then
                PANELCHECKIN.Visible = True
                FILLCHECKINGRID("")
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLPAYGRID(ByVal WHERECLAUSE As String)
        Try
            Dim OBJPAY As New ClsCommon
            Dim dt As DataTable = OBJPAY.search(" NAME, (CASE WHEN ROUND(CR,0) > 0 THEN CR ELSE ROUND(DR,0)*-1 END) AS BALANCE ", "", " TRIALBALANCE ", " AND SECONDARY = 'Sundry Creditors' AND (ROUND(DR,0) > 0 OR ROUND(CR,0) > 0) AND YEARID = " & YearId & " ORDER BY NAME")
            GRIDPAYDETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLRECGRID(ByVal WHERECLAUSE As String)
        Try
            Dim OBJREC As New ClsCommonMaster
            Dim dt As DataTable = OBJREC.search(" NAME, (CASE WHEN ROUND(DR,0) > 0 THEN DR ELSE ROUND(CR,0)*-1 END) AS BALANCE ", "", " TRIALBALANCE ", " AND SECONDARY = 'Sundry Debtors' AND (ROUND(DR,0) > 0 OR ROUND(CR,0) > 0) AND YEARID = " & YearId & " ORDER BY NAME")
            GRIDRECDETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLCHECKINGRID(ByVal WHERECLAUSE As String)
        Try
            WHERECLAUSE = " AND T.ARRIVAL = '" & Format(DateAdd(DateInterval.Day, 1, Mydate), "MM/dd/yyyy") & "' "

            If UserName <> "Admin" Then WHERECLAUSE = WHERECLAUSE & " AND T.BOOKEDBY = '" & UserName & "' "

            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable

            'dt = objclsCMST.search("*", "", " (SELECT CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS SRNO, HOTELBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS DATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME AS HOTELNAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, ISNULL(PLANMASTER.PLAN_NAME, '') AS MEALPLAN, BOOKING_TOTALROOMS AS TOTALROOMS, BOOKING_TOTALEXTRAADULT AS EXTRAADULTS, BOOKING_TOTALEXTRACHILD  AS EXTRACHILD, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME AS BOOKEDBY, HOTELBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, HOTELBOOKINGMASTER.BOOKING_BOOKTYPE AS TYPE, HOTELBOOKINGMASTER.BOOKING_CMPID AS CMPID, HOTELBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOTELBOOKINGMASTER.BOOKING_YEARID AS YEARID FROM HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID INNER JOIN LEDGERS ON HOTELBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOTELBOOKINGMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOTELBOOKINGMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN HOTELBOOKINGMASTER_DESC ON HOTELBOOKINGMASTER.BOOKING_NO = HOTELBOOKINGMASTER_DESC.BOOKING_NO AND HOTELBOOKINGMASTER.BOOKING_BOOKTYPE = HOTELBOOKINGMASTER_DESC.BOOKING_BOOKTYPE AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELBOOKINGMASTER_DESC.BOOKING_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN PLANMASTER ON HOTELBOOKINGMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOTELBOOKINGMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOTELBOOKINGMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOTELBOOKINGMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOTELBOOKINGMASTER.BOOKING_SALERETURN = 0) AND (HOTELBOOKINGMASTER.BOOKING_AMD_DONE = 0) UNION ALL SELECT CAST(0 AS BIT) AS CHK, HOLIDAYPACKAGEMASTER.BOOKING_NO AS SRNO, HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS, HOLIDAYPACKAGEMASTER.BOOKING_REFNO, HOLIDAYPACKAGEMASTER.BOOKING_DATE, GUESTMASTER.GUEST_NAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE, PLANMASTER.PLAN_NAME AS MEALPLAN, HOLIDAYPACKAGEMASTER_DESC.BOOKING_NOOFROOMS AS TOTALROOMS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRAADULTS AS EXTRAADULTS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRACHILDS  AS EXTRACHILD, HOLIDAYPACKAGEMASTER.BOOKING_PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME, HOLIDAYPACKAGEMASTER.BOOKING_SALEBALANCE, 'HOLIDAYPACKAGE' AS TYPE, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID FROM GUESTMASTER INNER JOIN HOLIDAYPACKAGEMASTER_GUESTDETAILS ON GUESTMASTER.GUEST_ID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_GUESTID AND GUESTMASTER.GUEST_CMPID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID AND GUESTMASTER.GUEST_LOCATIONID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID AND GUESTMASTER.GUEST_YEARID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID INNER JOIN HOLIDAYPACKAGEMASTER_DESC INNER JOIN HOLIDAYPACKAGEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO = HOLIDAYPACKAGEMASTER.BOOKING_NO AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOLIDAYPACKAGEMASTER.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOLIDAYPACKAGEMASTER.BOOKING_YEARID INNER JOIN BOOKEDBYMASTER ON HOLIDAYPACKAGEMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID AND HOLIDAYPACKAGEMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID ON HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_NO = HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID INNER JOIN LEDGERS ON HOLIDAYPACKAGEMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOLIDAYPACKAGEMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN PLANMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOLIDAYPACKAGEMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOLIDAYPACKAGEMASTER.BOOKING_AMD_DONE = 0) AND (HOLIDAYPACKAGEMASTER.BOOKING_SALERETURN = 0)) AS T ", WHERECLAUSE & " AND T.CMPID =" & CmpId & " AND T.LOCATIONID = " & Locationid & " AND T.YEARID = " & YearId & " ORDER BY T.SRNO")

            'AS PER JOJO SIR RECOMMENDATION, CHECKIN SHOULD BE VISIBLE IRRESPCTIVE OF YEAR BOOKING DONE, SO REMOVED YEARID CLAUSE
            dt = objclsCMST.search("*", "", " (SELECT CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS SRNO, HOTELBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS DATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME AS HOTELNAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, ISNULL(PLANMASTER.PLAN_NAME, '') AS MEALPLAN, BOOKING_TOTALROOMS AS TOTALROOMS, BOOKING_TOTALEXTRAADULT AS EXTRAADULTS, BOOKING_TOTALEXTRACHILD  AS EXTRACHILD, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME AS BOOKEDBY, HOTELBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, HOTELBOOKINGMASTER.BOOKING_BOOKTYPE AS TYPE, HOTELBOOKINGMASTER.BOOKING_CMPID AS CMPID, HOTELBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOTELBOOKINGMASTER.BOOKING_YEARID AS YEARID FROM HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID INNER JOIN LEDGERS ON HOTELBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOTELBOOKINGMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOTELBOOKINGMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN HOTELBOOKINGMASTER_DESC ON HOTELBOOKINGMASTER.BOOKING_NO = HOTELBOOKINGMASTER_DESC.BOOKING_NO AND HOTELBOOKINGMASTER.BOOKING_BOOKTYPE = HOTELBOOKINGMASTER_DESC.BOOKING_BOOKTYPE AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELBOOKINGMASTER_DESC.BOOKING_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN PLANMASTER ON HOTELBOOKINGMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOTELBOOKINGMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOTELBOOKINGMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOTELBOOKINGMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOTELBOOKINGMASTER.BOOKING_SALERETURN = 0) AND (HOTELBOOKINGMASTER.BOOKING_AMD_DONE = 0) UNION ALL SELECT CAST(0 AS BIT) AS CHK, HOLIDAYPACKAGEMASTER.BOOKING_NO AS SRNO, HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS, HOLIDAYPACKAGEMASTER.BOOKING_REFNO, HOLIDAYPACKAGEMASTER.BOOKING_DATE, GUESTMASTER.GUEST_NAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE, PLANMASTER.PLAN_NAME AS MEALPLAN, HOLIDAYPACKAGEMASTER_DESC.BOOKING_NOOFROOMS AS TOTALROOMS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRAADULTS AS EXTRAADULTS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRACHILDS  AS EXTRACHILD, HOLIDAYPACKAGEMASTER.BOOKING_PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME, HOLIDAYPACKAGEMASTER.BOOKING_SALEBALANCE, 'HOLIDAYPACKAGE' AS TYPE, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID FROM GUESTMASTER INNER JOIN HOLIDAYPACKAGEMASTER_GUESTDETAILS ON GUESTMASTER.GUEST_ID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_GUESTID AND GUESTMASTER.GUEST_CMPID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID AND GUESTMASTER.GUEST_LOCATIONID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID AND GUESTMASTER.GUEST_YEARID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID INNER JOIN HOLIDAYPACKAGEMASTER_DESC INNER JOIN HOLIDAYPACKAGEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO = HOLIDAYPACKAGEMASTER.BOOKING_NO AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOLIDAYPACKAGEMASTER.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOLIDAYPACKAGEMASTER.BOOKING_YEARID INNER JOIN BOOKEDBYMASTER ON HOLIDAYPACKAGEMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID AND HOLIDAYPACKAGEMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID ON HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_NO = HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID INNER JOIN LEDGERS ON HOLIDAYPACKAGEMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOLIDAYPACKAGEMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN PLANMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOLIDAYPACKAGEMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOLIDAYPACKAGEMASTER.BOOKING_AMD_DONE = 0) AND (HOLIDAYPACKAGEMASTER.BOOKING_SALERETURN = 0)) AS T ", WHERECLAUSE & " AND T.CMPID =" & CmpId & " ORDER BY T.SRNO")
            
            GRIDCHECKINDETAILS.DataSource = dt
            If dt.Rows.Count > 0 Then
                GRIDCHECKIN.FocusedRowHandle = GRIDCHECKIN.RowCount - 1
                GRIDCHECKIN.TopRowIndex = GRIDCHECKIN.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWPAYFORM()
        Try
            If GRIDPAY.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDPAY.GetFocusedDataRow
                Dim NAME As String = dtrow("NAME")
                If NAME <> "" Then
                    Dim objlb As New LedgerBook
                    objlb.TEMPNAME = NAME
                    objlb.MdiParent = MDIMain
                    objlb.Show()
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWRECFORM()
        Try
            If GRIDREC.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDREC.GetFocusedDataRow
                Dim NAME As String = dtrow("NAME")
                If NAME <> "" Then
                    Dim objlb As New LedgerBook
                    objlb.TEMPNAME = NAME
                    objlb.MdiParent = MDIMain
                    objlb.Show()
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDREC_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles GRIDREC.DoubleClick
        Try
            SHOWRECFORM()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDPAY_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles GRIDPAY.DoubleClick
        Try
            SHOWPAYFORM()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWCHECKINFORM(ByVal editval As Boolean, ByVal BOOKINGNO As Integer, ByVal TYPE As String)
        Try
            If (editval = False) Or (editval = True And GRIDCHECKIN.RowCount > 0) Then
                If TYPE = "HOLIDAYPACKAGE" Then
                    Dim OBJBOOKING As New HolidayPackage
                    OBJBOOKING.MdiParent = MDIMain
                    OBJBOOKING.edit = editval
                    OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                    OBJBOOKING.Show()
                Else
                    Dim OBJBOOKING As New HotelBookings
                    OBJBOOKING.MdiParent = MDIMain
                    OBJBOOKING.FRMSTRING = TYPE
                    OBJBOOKING.edit = editval
                    OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                    OBJBOOKING.Show()
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDCHECKIN_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles GRIDCHECKIN.DoubleClick
        Try
            SHOWCHECKINFORM(True, GRIDCHECKIN.GetFocusedRowCellValue("SRNO"), GRIDCHECKIN.GetFocusedRowCellValue("TYPE"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class