
Imports BL

Public Class RoomInventory

    Private Sub RoomInventory_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.Alt = True And e.KeyCode = Windows.Forms.Keys.S Then       'for Saving
                Call cmdshowdetails_Click(sender, e)
            ElseIf (e.Alt = True And e.KeyCode = Windows.Forms.Keys.X) Or (e.KeyCode = Windows.Forms.Keys.Escape) Then   'for Exit
                Me.Close()
            ElseIf e.KeyCode = Keys.Oemcomma Then
                e.SuppressKeyPress = True
            ElseIf e.KeyCode = Keys.Enter Then
                SendKeys.Send("{Tab}")
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub RoomInventory_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Try
            CLEAR()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Sub CLEAR()
        Try
            GRIDINVENTORY.RowCount = 0
            dtfrom.Value = Mydate
            dtto.Value = Mydate
            dtto.Value = DateAdd(DateInterval.Day, 7, dtto.Value)
            cmbhotelcode.Text = ""
            cmbhotelname.Text = ""
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmbhotelcode_Enter(ByVal sender As Object, ByVal e As System.EventArgs) Handles cmbhotelcode.Enter
        Try
            If cmbhotelcode.Text.Trim = "" Then fillHOTELCODE(cmbhotelcode)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmbhotelname_Enter(ByVal sender As Object, ByVal e As System.EventArgs) Handles cmbhotelname.Enter
        Try
            If cmbhotelname.Text.Trim = "" Then fillHOTEL(cmbhotelname)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmbhotelcode_Validating(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs) Handles cmbhotelcode.Validating
        Try
            If cmbhotelcode.Text.Trim <> "" Then HOTELCODEVALIDATE(cmbhotelcode, cmbhotelname, e, Me, TXTADD)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmbhotelname_Validating(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs) Handles cmbhotelname.Validating
        Try
            If cmbhotelname.Text.Trim <> "" Then HOTELvalidate(cmbhotelname, cmbhotelcode, e, Me, TXTADD)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Function ERRORVALID() As Boolean
        Try
            Dim BLN As Boolean = True
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search("HOTEL_INVENTORY", "", " HOTELMASTER", " AND HOTEL_NAME = '" & cmbhotelname.Text.Trim & "' AND HOTEL_CMPID = " & CmpId & " AND HOTEL_LOCATIONID = " & Locationid & " AND HOTEL_YEARID = " & YearId)
            If DT.Rows.Count > 0 Then
                If Convert.ToBoolean(DT.Rows(0).Item(0)) = False Then
                    EP.SetError(cmbhotelname, "Inventory Not Present, Select Inventory Option in Hotel Master")
                    BLN = False
                End If
            End If

            If cmbhotelname.Text.Trim = "" Then
                EP.SetError(cmbhotelname, "Select Hotel to Display Inventory")
                BLN = False
            End If

            If dtto.Value.Date < dtfrom.Value.Date Then
                EP.SetError(dtto, "Invalid Date Selected")
                BLN = False
            End If

            Return BLN
        Catch ex As Exception
            Throw ex
        End Try
    End Function

    Private Sub cmdshowdetails_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdshowdetails.Click
        Try
            EP.Clear()
            If Not ERRORVALID() Then
                Exit Sub
            End If
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLGRID()
        Try
            GRIDINVENTORY.RowCount = 0
            GRIDINVENTORY.ColumnCount = 0
            Dim COLS As Integer = DateDiff(DateInterval.Day, dtfrom.Value.Date, dtto.Value.Date) + 1
            Dim ROWS As Integer = 0
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search(" SUM(HOTELMASTER_ROOMDESC.HOTEL_NOOFROOMS)", "", " HOTELMASTER INNER JOIN HOTELMASTER_ROOMDESC ON HOTELMASTER.HOTEL_ID = HOTELMASTER_ROOMDESC.HOTEL_ID AND HOTELMASTER.HOTEL_CMPID = HOTELMASTER_ROOMDESC.HOTEL_CMPID AND HOTELMASTER.HOTEL_LOCATIONID = HOTELMASTER_ROOMDESC.HOTEL_LOCATIONID AND HOTELMASTER.HOTEL_YEARID = HOTELMASTER_ROOMDESC.HOTEL_YEARID ", " AND HOTELMASTER.HOTEL_NAME = '" & cmbhotelname.Text.Trim & "' AND HOTELMASTER.HOTEL_CMPID = " & CmpId & " AND HOTELMASTER.HOTEL_LOCATIONID = " & Locationid & " AND HOTELMASTER.HOTEL_YEARID = " & YearId)
            GRIDINVENTORY.ColumnCount = COLS

            ROWS = DT.Rows(0).Item(0)

            DT = OBJCMN.search(" COUNT(*)", "", " HOTELMASTER_ROOMDESC INNER JOIN HOTELMASTER ON HOTELMASTER_ROOMDESC.HOTEL_ID = HOTELMASTER.HOTEL_ID AND  HOTELMASTER_ROOMDESC.HOTEL_CMPID = HOTELMASTER.HOTEL_CMPID  AND  HOTELMASTER_ROOMDESC.HOTEL_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID  AND HOTELMASTER_ROOMDESC.HOTEL_YEARID  = HOTELMASTER.HOTEL_YEARID ", " AND HOTELMASTER.HOTEL_NAME = '" & cmbhotelname.Text.Trim & "' AND HOTELMASTER.HOTEL_CMPID = " & CmpId & " AND HOTELMASTER.HOTEL_LOCATIONID = " & Locationid & " AND HOTELMASTER.HOTEL_YEARID = " & YearId)
            ROWS = ROWS + DT.Rows(0).Item(0)
            GRIDINVENTORY.RowCount = ROWS

            COLHEADER()
            ROWHEADER()

            
            Dim TEMPDATE As Date = dtfrom.Value.Date  'FOR CHECKING IN CELLS

            'THIS ODE RETRIEVES ONLY HOTELBOOKINGS
            'DT = OBJCMN.search(" GUEST_NAME AS GUESTNAME AS GUESTNAME, HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, BOOKING_TOTALNIGHTS AS DAYS, HOTELMASTER.HOTEL_NAME AS HOTELNAME, ROOMTYPEMASTER.ROOMTYPE_NAME AS ROOMTYPE, HOTELBOOKINGMASTER_DESC.BOOKING_NOOFROOMS  AS NOOFROOMS", "", " HOTELBOOKINGMASTER INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID LEFT OUTER JOIN HOTELBOOKINGMASTER_DESC ON HOTELBOOKINGMASTER.BOOKING_NO = HOTELBOOKINGMASTER_DESC.BOOKING_NO AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELBOOKINGMASTER_DESC.BOOKING_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELBOOKINGMASTER_DESC.BOOKING_YEARID LEFT OUTER JOIN ROOMTYPEMASTER ON HOTELBOOKINGMASTER_DESC.BOOKING_ROOMTYPEID = ROOMTYPEMASTER.ROOMTYPE_ID AND HOTELBOOKINGMASTER_DESC.BOOKING_CMPID = ROOMTYPEMASTER.ROOMTYPE_CMPID AND HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID = ROOMTYPEMASTER.ROOMTYPE_LOCATIONID AND HOTELBOOKINGMASTER_DESC.BOOKING_YEARID = ROOMTYPEMASTER.ROOMTYPE_YEARID INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID", " AND HOTELMASTER.HOTEL_NAME = '" & cmbhotelname.Text.Trim & "' AND (HOTELBOOKINGMASTER.BOOKING_ARRIVAL BETWEEN '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "' OR HOTELBOOKINGMASTER.BOOKING_DEPARTURE BETWEEN '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "') AND HOTELBOOKINGMASTER.BOOKING_CMPID = " & CmpId & " AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = " & Locationid & " AND HOTELBOOKINGMASTER.BOOKING_YEARID = " & YearId)
            DT = OBJCMN.search(" * ", "", " (SELECT GUEST_NAME AS GUESTNAME, HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, HOTELBOOKINGMASTER.BOOKING_TOTALNIGHTS AS DAYS, HOTELMASTER.HOTEL_NAME AS HOTELNAME, ROOMTYPEMASTER.ROOMTYPE_NAME AS ROOMTYPE, HOTELBOOKINGMASTER_DESC.BOOKING_NOOFROOMS AS NOOFROOMS, HOTELBOOKINGMASTER.BOOKING_CMPID AS CMPID, HOTELBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID , HOTELBOOKINGMASTER.BOOKING_YEARID AS YEARID FROM HOTELBOOKINGMASTER INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID LEFT OUTER JOIN HOTELBOOKINGMASTER_DESC ON HOTELBOOKINGMASTER.BOOKING_BOOKTYPE = HOTELBOOKINGMASTER_DESC.BOOKING_BOOKTYPE AND HOTELBOOKINGMASTER.BOOKING_NO = HOTELBOOKINGMASTER_DESC.BOOKING_NO AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELBOOKINGMASTER_DESC.BOOKING_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELBOOKINGMASTER_DESC.BOOKING_YEARID LEFT OUTER JOIN ROOMTYPEMASTER ON HOTELBOOKINGMASTER_DESC.BOOKING_ROOMTYPEID = ROOMTYPEMASTER.ROOMTYPE_ID AND HOTELBOOKINGMASTER_DESC.BOOKING_CMPID = ROOMTYPEMASTER.ROOMTYPE_CMPID AND HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID = ROOMTYPEMASTER.ROOMTYPE_LOCATIONID AND HOTELBOOKINGMASTER_DESC.BOOKING_YEARID = RoomTypeMaster.ROOMTYPE_YEARID UNION ALL SELECT HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS AS GUESTNAME, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE AS ARRIVAL, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE AS DEPARTURE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_NIGHTS AS DAYS, HOTEL_NAME AS HOTELNAME, ROOMTYPE_NAME AS ROOMTYPE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_NOOFROOMS AS NOOFROOMS, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID , HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID FROM HOLIDAYPACKAGEMASTER INNER JOIN HOLIDAYPACKAGEMASTER_DESC ON HOLIDAYPACKAGEMASTER.BOOKING_NO = HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO AND HOLIDAYPACKAGEMASTER.BOOKING_CMPID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID INNER JOIN ROOMTYPEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_ROOMTYPEID = ROOMTYPEMASTER.ROOMTYPE_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = ROOMTYPEMASTER.ROOMTYPE_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = ROOMTYPEMASTER.ROOMTYPE_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = ROOMTYPEMASTER.ROOMTYPE_YEARID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HotelMaster.HOTEL_YEARID UNION ALL SELECT INTERNATIONALBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS GUESTNAME, INTERNATIONALBOOKINGMASTER_DESC.BOOKING_ARRIVALDATE AS ARRIVAL,INTERNATIONALBOOKINGMASTER_DESC.BOOKING_DEPARTUREDATE AS DEPARTURE, INTERNATIONALBOOKINGMASTER_DESC.BOOKING_NIGHTS AS DAYS, HOTEL_NAME AS HOTELNAME, ROOMTYPE_NAME AS ROOMTYPE, INTERNATIONALBOOKINGMASTER_DESC.BOOKING_NOOFROOMS AS NOOFROOMS, INTERNATIONALBOOKINGMASTER.BOOKING_CMPID AS CMPID, INTERNATIONALBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID , INTERNATIONALBOOKINGMASTER.BOOKING_YEARID AS YEARID FROM INTERNATIONALBOOKINGMASTER INNER JOIN INTERNATIONALBOOKINGMASTER_DESC ON INTERNATIONALBOOKINGMASTER.BOOKING_NO = INTERNATIONALBOOKINGMASTER_DESC.BOOKING_NO AND INTERNATIONALBOOKINGMASTER.BOOKING_CMPID = INTERNATIONALBOOKINGMASTER_DESC.BOOKING_CMPID AND INTERNATIONALBOOKINGMASTER.BOOKING_LOCATIONID = INTERNATIONALBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND INTERNATIONALBOOKINGMASTER.BOOKING_YEARID = INTERNATIONALBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN ROOMTYPEMASTER ON INTERNATIONALBOOKINGMASTER_DESC.BOOKING_ROOMTYPEID = ROOMTYPEMASTER.ROOMTYPE_ID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_CMPID = ROOMTYPEMASTER.ROOMTYPE_CMPID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_LOCATIONID = ROOMTYPEMASTER.ROOMTYPE_LOCATIONID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_YEARID = ROOMTYPEMASTER.ROOMTYPE_YEARID INNER JOIN HOTELMASTER ON INTERNATIONALBOOKINGMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND INTERNATIONALBOOKINGMASTER_DESC.BOOKING_YEARID = HotelMaster.HOTEL_YEARID ) AS T ", " AND T.HOTELNAME = '" & cmbhotelname.Text.Trim & "' AND (T.ARRIVAL BETWEEN '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "' OR T.DEPARTURE BETWEEN '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "') AND T.CMPID = " & CmpId & " AND T.LOCATIONID = " & Locationid & " AND T.YEARID = " & YearId)
            If DT.Rows.Count > 0 Then
                For Each DTROW As DataRow In DT.Rows

                    'FOR ROOMS
                    For i As Integer = 1 To DTROW("NOOFROOMS")

                        COLS = 0
                        ROWS = 0

                        'GET COL NO FIRST (WE CAN GET COL NO BY DATEDIFF OF FROM DATE AND ARRIVAL DATE)
                        If Convert.ToDateTime(DTROW("ARRIVAL")).Date >= dtfrom.Value.Date Then COLS = DateDiff(DateInterval.Day, dtfrom.Value.Date, Convert.ToDateTime(DTROW("ARRIVAL")).Date)

                        'GETTING ROW NO (CHECK FOR ROOMTYPE AND ROW HEADER)
LINE1:
                        For Each ROW As DataGridViewRow In GRIDINVENTORY.Rows
                            If ROW.HeaderCell.Value = DTROW("ROOMTYPE") And ROW.Cells(COLS).Value = Nothing Then
                                ROWS = ROW.Index
                                Exit For
                            End If
                        Next

                        'FOR NO OF NIGHTS
                        For J As Integer = 1 To DTROW("DAYS")

                            If COLS < GRIDINVENTORY.ColumnCount Then
                                If GRIDINVENTORY.Item(COLS, ROWS).Value = Nothing Then
                                    GRIDINVENTORY.Item(COLS, ROWS).Style.BackColor = Color.LightGreen
                                    GRIDINVENTORY.Item(COLS, ROWS).Value = DTROW("GUESTNAME")

                                    COLS = COLS + 1
                                Else
                                    GRIDINVENTORY.Item(COLS, ROWS + 1).Style.BackColor = Color.LightGreen
                                    GRIDINVENTORY.Item(COLS, ROWS + 1).Value = DTROW("GUESTNAME")

                                    COLS = COLS + 1
                                End If
                            End If
                        Next

                    Next

                Next
            End If
            GRIDINVENTORY.ClearSelection()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub COLHEADER()
        Try
            Dim HEADERDATE As Date = dtfrom.Value.Date
            For Each COL As DataGridViewColumn In GRIDINVENTORY.Columns
                COL.HeaderText = Format(DateAdd(DateInterval.Day, COL.Index, HEADERDATE.Date), "dd-MMM (dddd)")
                COL.Width = 150
            Next
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub ROWHEADER()
        Try
            Dim CURRENTROW As Integer = 0
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search(" ROOMTYPEMASTER.ROOMTYPE_NAME AS ROOMTYPE, HOTELMASTER_ROOMDESC.HOTEL_NOOFROOMS AS NOOFROOMS", "", " HOTELMASTER INNER JOIN HOTELMASTER_ROOMDESC ON HOTELMASTER.HOTEL_ID = HOTELMASTER_ROOMDESC.HOTEL_ID AND HOTELMASTER.HOTEL_CMPID = HOTELMASTER_ROOMDESC.HOTEL_CMPID AND HOTELMASTER.HOTEL_LOCATIONID = HOTELMASTER_ROOMDESC.HOTEL_LOCATIONID AND HOTELMASTER.HOTEL_YEARID = HOTELMASTER_ROOMDESC.HOTEL_YEARID INNER JOIN ROOMTYPEMASTER ON HOTELMASTER_ROOMDESC.HOTEL_ROOMTYPEID = ROOMTYPEMASTER.ROOMTYPE_ID AND HOTELMASTER_ROOMDESC.HOTEL_CMPID = ROOMTYPEMASTER.ROOMTYPE_CMPID AND HOTELMASTER_ROOMDESC.HOTEL_LOCATIONID = ROOMTYPEMASTER.ROOMTYPE_LOCATIONID AND HOTELMASTER_ROOMDESC.HOTEL_YEARID = ROOMTYPEMASTER.ROOMTYPE_YEARID ", " AND HOTELMASTER.HOTEL_NAME = '" & cmbhotelname.Text.Trim & "' AND HOTELMASTER.HOTEL_CMPID = " & CmpId & " AND HOTELMASTER.HOTEL_LOCATIONID = " & Locationid & " AND HOTELMASTER.HOTEL_YEARID = " & YearId & " ORDER BY ROOMTYPEMASTER.ROOMTYPE_NAME")
            For Each DTROW As DataRow In DT.Rows
                For I As Integer = CURRENTROW To (DTROW("NOOFROOMS") + CURRENTROW) - 1
                    GRIDINVENTORY.Rows(I).HeaderCell.Value = DTROW("ROOMTYPE")
                Next
                CURRENTROW = CURRENTROW + DTROW("NOOFROOMS") + 1
            Next
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class