
Imports BL

Public Class CarBookingPurGridReport

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Public FRMSTRING, WHERECLAUSE As String

    Private Sub CarBookingSaleGridReport_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim objclsCMST As New ClsCommonMaster
            'Dim dt As DataTable = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_DATE AS BOOKINGDATE, LEDGERS.Acc_cmpname AS ACCNAME, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0) AS PURSTARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0) AS PURENDKMS, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) AS PURTOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END  AS PUREXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0) AS PURSTARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0) AS PURENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) AS PURTOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END  AS PUREXTRATIME, ISNULL(DRIVERMASTER.DRIVER_NAME, '') AS DRIVERNAME, ISNULL(VEHICLEMASTER.VEHICLE_NAME, '') AS VEHICLENAME, ISNULL(CARBOOKINGMASTER_DESC.BOOKING_VEHICLENO, '') AS VEHICLENO, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_OTHERCHGS,0) AS PUROTHERCHGS, ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE , CARBOOKINGMASTER.BOOKING_HRKMRATEPUR AS PURTOTALAMT, ISNULL(ROUND(((CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END) * CARBOOKINGMASTER.BOOKING_KMSRATEPUR),2),0) AS PUREXTRAKMAMT, ISNULL(ROUND(((CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END) * CARBOOKINGMASTER.BOOKING_HRSRATEPUR ),2),0) AS PUREXTRAHRAMT, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_GTOTAL AS PURGTOTAL ", "", " DRIVERMASTER RIGHT OUTER JOIN CARBOOKINGMASTER INNER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id INNER JOIN GUESTMASTER ON CARBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID INNER JOIN CARBOOKINGMASTER_DESC ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_DESC.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN VEHICLEMASTER ON CARBOOKINGMASTER_DESC.BOOKING_VEHICLEID = VEHICLEMASTER.VEHICLE_ID ON DRIVERMASTER.DRIVER_ID = CARBOOKINGMASTER_DESC.BOOKING_DRIVERID LEFT OUTER JOIN TAXMASTER ON CARBOOKINGMASTER.BOOKING_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO AND  CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id", WHERECLAUSE & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")
            Dim dt As DataTable = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_DATE AS DATE, LEDGERS.Acc_cmpname AS ACCNAME, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0) AS PURSTARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0) AS PURENDKMS, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) AS PURTOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END  AS PUREXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0) AS PURSTARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0) AS PURENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) AS PURTOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END  AS PUREXTRATIME, ISNULL(DRIVERMASTER.DRIVER_NAME, '') AS DRIVERNAME, ISNULL(VEHICLEMASTER.VEHICLE_NAME, '') AS VEHICLENAME, ISNULL(CARBOOKINGMASTER_DESC.BOOKING_VEHICLENO, '') AS VEHICLENO, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_OTHERCHGS,0) AS PUROTHERCHGS, ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE , CARBOOKINGMASTER.BOOKING_HRKMRATEPUR AS PURTOTALAMT, ISNULL(ROUND(((CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END) * CARBOOKINGMASTER.BOOKING_KMSRATEPUR),2),0) AS PUREXTRAKMAMT, ISNULL(ROUND(((CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END) * CARBOOKINGMASTER.BOOKING_HRSRATEPUR ),2),0) AS PUREXTRAHRAMT, ISNULL(CARBOOKINGMASTER.BOOKING_ALLOWANCEPUR,0) AS PURALLOWANCE, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_GTOTAL AS PURGTOTAL, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day,CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO))+1 ELSE 0 END  AS DAYS, CASE WHEN ISNULL(CARBOOKINGMASTER.BOOKING_TYPE,'LOCAL') = 'OUTSTATION' THEN (DATEDIFF(day,CARBOOKINGMASTER.BOOKING_PACKAGEFROM, CARBOOKINGMASTER.BOOKING_PACKAGETO)) ELSE 0 END  AS NIGHTS ", "", " LEDGERS AS PURLEDGERS INNER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON PURLEDGERS.Acc_id = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_PURLEDGERID RIGHT OUTER JOIN DRIVERMASTER RIGHT OUTER JOIN CARBOOKINGMASTER INNER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id INNER JOIN GUESTMASTER ON CARBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID INNER JOIN CARBOOKINGMASTER_DESC ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_DESC.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN VEHICLEMASTER ON CARBOOKINGMASTER_DESC.BOOKING_VEHICLEID = VEHICLEMASTER.VEHICLE_ID ON DRIVERMASTER.DRIVER_ID = CARBOOKINGMASTER_DESC.BOOKING_DRIVERID LEFT OUTER JOIN TAXMASTER ON CARBOOKINGMASTER.BOOKING_TAXID = TAXMASTER.tax_id ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO = CARBOOKINGMASTER.BOOKING_NO AND CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID = CARBOOKINGMASTER.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id ", WHERECLAUSE & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub CarBookingSaleGridReport_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub ExcelExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ExcelExport.Click
        Try
            Dim PATH As String = "" = ""
            If FileIO.FileSystem.FileExists(PATH) = True Then FileIO.FileSystem.DeleteFile(PATH)
            PATH = Application.StartupPath & "\Purchase Report.XLS"

            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True

            Dim workbook As String = PATH
            If FileIO.FileSystem.FileExists(PATH) = True Then Interaction.GetObject(workbook).close(False)
            GC.Collect()
            'For Each proc In System.Diagnostics.Process.GetProcessesByName("Excel")
            '    proc.Kill()
            'Next

            opti.SheetName = ""
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Purchase Report", gridbill.VisibleColumns.Count + gridbill.GroupCount, "", "")

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub showform(ByVal editval As Boolean, ByVal BOOKINGNO As Integer)
        Try
            If (editval = False) Or (editval = True And gridbill.RowCount > 0) Then
                Dim OBJBOOKING As New CarBooking
                OBJBOOKING.MdiParent = MDIMain
                OBJBOOKING.edit = editval
                OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                OBJBOOKING.Show()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles gridbill.DoubleClick
        Try
            showform(True, gridbill.GetFocusedRowCellValue("BOOKINGNO"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class