
Imports BL

Public Class CarBookingInvoiceDetailsGridReport

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Public FRMSTRING, WHERECLAUSE As String

    Private Sub CarBookingDetails_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable
            dt = objclsCMST.search(" CARBOOKINGMASTER.BOOKING_NO AS BILL, CARBOOKINGMASTER.BOOKING_SPECIALREMARKS AS SPECIALREMARKS, CARBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BILLINITIALS, CARBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, CARBOOKINGMASTER.BOOKING_REFNO AS REFNO, CARBOOKINGMASTER.BOOKING_DATE AS BOOKINGDATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, ISNULL(GUESTMASTER.GUEST_EMAIL, '') AS EMAIL, LEDGERS.Acc_cmpname AS ACCNAME, CARBOOKINGMASTER.BOOKING_PACKAGEFROM AS [FROMDATE], CARBOOKINGMASTER.BOOKING_PACKAGETO AS [TO], CARBOOKINGMASTER.BOOKING_TOTALPURAMT AS PURTOTAL, ISNULL(CARBOOKINGMASTER.BOOKING_OTHERCHGS,0) as OTHERCHGS ,  CARBOOKINGMASTER.BOOKING_GRANDTOTAL AS GRANDTOTAL, USERMASTER.User_Name AS USERNAME, CARBOOKINGMASTER.BOOKING_CANCELLED AS CANCELLED, CARBOOKINGMASTER.BOOKING_DISPUTE AS DISPUTED, CARBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, CARBOOKINGMASTER.BOOKING_BILLCHECKED AS BILLCHECKED, ISNULL(PURTAXMASTER.tax_name, '') AS PURTAXNAME, ISNULL(CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXAMT, 0) AS PURTAXAMT, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(CARBOOKINGMASTER.BOOKING_TAX, 0) AS TAXAMT, CARBOOKINGMASTER.BOOKING_SUBTOTAL AS SUBTOTAL, CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NETT AS PURSUBTOTAL, ISNULL(CARBOOKINGMASTER.BOOKING_CONFIRMEDBY, '') AS CONFIRMEDBY, ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0) AS STARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0) AS ENDKMS, ISNULL( BOOKING_TYPE,'LOCAL') AS BOOKINGTYPE, (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0)) AS TOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0))-40 ELSE (ISNULL(CARBOOKINGMASTER.BOOKING_ENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTKMS, 0)) END) END  AS EXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0) AS STARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0) AS ENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0)) AS TOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0))-4 ELSE (ISNULL(CARBOOKINGMASTER.BOOKING_ENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_STARTTIME, 0)) END) END  AS EXTRATIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0) AS PURSTARTKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0) AS PURENDKMS, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) AS PURTOTALKMS,  CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-80 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0))-40 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDKMS, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTKMS, 0)) END) END  AS PUREXTRAKMS, ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0) AS PURSTARTTIME, ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0) AS PURENDTIME, (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) AS PURTOTALTIME, CASE WHEN ISNULL(BOOKING_TYPE , 'LOCAL') = 'LOCAL' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-8 ELSE (CASE WHEN BOOKING_TYPE  = '4HRS 40KMS' THEN (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0))-4 ELSE  (ISNULL(CARBOOKINGMASTER.BOOKING_PURENDTIME, 0)-ISNULL(CARBOOKINGMASTER.BOOKING_PURSTARTTIME, 0)) END) END  AS PUREXTRATIME, ISNULL(DRIVERMASTER.DRIVER_NAME, '') AS DRIVERNAME, ISNULL(VEHICLEMASTER.VEHICLE_NAME, '') AS VEHICLENAME, ISNULL(CARBOOKINGMASTER_DESC.BOOKING_VEHICLENO, '') AS VEHICLENO ", "", " DRIVERMASTER RIGHT OUTER JOIN CARBOOKINGMASTER INNER JOIN LEDGERS ON CARBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id INNER JOIN USERMASTER ON CARBOOKINGMASTER.BOOKING_USERID = USERMASTER.User_id INNER JOIN GUESTMASTER ON CARBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID INNER JOIN CARBOOKINGMASTER_DESC ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_DESC.BOOKING_NO AND CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN VEHICLEMASTER ON CARBOOKINGMASTER_DESC.BOOKING_VEHICLEID = VEHICLEMASTER.VEHICLE_ID ON DRIVERMASTER.DRIVER_ID = CARBOOKINGMASTER_DESC.BOOKING_DRIVERID LEFT OUTER JOIN TAXMASTER ON CARBOOKINGMASTER.BOOKING_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN CARBOOKINGMASTER_PURCHASEDETAILS ON CARBOOKINGMASTER.BOOKING_NO = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_NO AND  CARBOOKINGMASTER.BOOKING_YEARID = CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_YEARID LEFT OUTER JOIN TAXMASTER AS PURTAXMASTER ON CARBOOKINGMASTER_PURCHASEDETAILS.BOOKING_TAXID = PURTAXMASTER.tax_id ", " AND CARBOOKINGMASTER.BOOKING_YEARID = " & YearId & WHERECLAUSE & " ORDER BY CARBOOKINGMASTER.BOOKING_NO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub CarBookingDetails_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub ExcelExport_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ExcelExport.Click
        Try
            Dim PATH As String = ""
            If FileIO.FileSystem.FileExists(PATH) = True Then FileIO.FileSystem.DeleteFile(PATH)
            PATH = Application.StartupPath & "\Invoice Details.XLS"

            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True

            Dim workbook As String = PATH
            If FileIO.FileSystem.FileExists(PATH) = True Then Interaction.GetObject(workbook).close(False)
            GC.Collect()

            Dim PERIOD As String = ""
            PERIOD = AccFrom & " - " & AccTo

            opti.SheetName = "Invoice Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Invoice Details", gridbill.VisibleColumns.Count + gridbill.GroupCount, "", PERIOD)

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class