
Imports BL

Public Class CheckInList

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Dim fromD
    Dim toD
    Dim a1, a2, a3, a4 As String
    Dim a11, a12, a13, a14 As String

    Private Sub CheckInList_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Or (e.KeyCode = Keys.X And e.Alt = True) Then
                Me.Close()
            ElseIf e.KeyCode = Keys.N And e.Alt = True Then
                showform(False, 0, "BOOKING")
            ElseIf e.KeyCode = Keys.O And e.Alt = True Then
                cmdok_Click(sender, e)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal WHERECLAUSE As String)
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable

            If chkdate.CheckState = CheckState.Checked Then
                WHERECLAUSE = " AND T.ARRIVAL >= '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND T.ARRIVAL <= '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "' "
            Else
                If ClientName = "TNL" Then
                    dt = objclsCMST.search("ISNULL(CHECKIN_DAYS,0) AS DAYS", "", "CHECKINDAYS ", " AND T.ARRIVAL >= '" & Format(Mydate, "MM/dd/yyyy") & "' AND CHECKINDAYS.CHECKIN_CMPID =" & CmpId & " ")
                Else
                    dt = objclsCMST.search("ISNULL(CHECKIN_DAYS,0) AS DAYS", "", "CHECKINDAYS ", WHERECLAUSE & " AND CHECKINDAYS.CHECKIN_CMPID =" & CmpId & " ")
                    If dt.Rows.Count > 0 Then
                        WHERECLAUSE = " AND T.ARRIVAL = '" & Format(DateAdd(DateInterval.Day, Val(dt.Rows(0).Item("DAYS")), Mydate), "MM/dd/yyyy") & "' "
                    Else
                        WHERECLAUSE = " AND T.ARRIVAL = '" & Format(DateAdd(DateInterval.Day, 1, Mydate), "MM/dd/yyyy") & "' "
                    End If
                End If
            End If





            If ClientName <> "CLASSIC" Then
                If UserName <> "Admin" Then WHERECLAUSE = WHERECLAUSE & " AND T.BOOKEDBY = '" & UserName & "' "
            End If


            'dt = objclsCMST.search(" CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS [DATE], GUESTMASTER.GUEST_NAME AS GUESTNAME , HOTELMASTER.HOTEL_NAME AS HOTELNAME,  HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME aS BOOKEDBY, BOOKING_SALEBALANCE AS BALANCE, BOOKING_BOOKTYPE AS TYPE ", "", " HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID ", WHERECLAUSE & " AND BOOKING_CANCELLED = 'FALSE' AND BOOKING_SALERETURN = 0 AND BOOKING_CMPID =" & CmpId & " AND BOOKING_LOCATIONID = " & Locationid & " AND BOOKING_YEARID = " & YearId & " ORDER BY HOTELBOOKINGMASTER.BOOKING_NO")
            If ClientName = "PARAMOUNT" Then
                dt = objclsCMST.search("*", "", " (SELECT CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS SRNO, HOTELBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS DATE, GUESTMASTER.GUEST_NAME AS GUESTNAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME AS HOTELNAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, ISNULL(PLANMASTER.PLAN_NAME, '') AS MEALPLAN, BOOKING_TOTALROOMS AS TOTALROOMS, BOOKING_TOTALEXTRAADULT AS EXTRAADULTS, BOOKING_TOTALEXTRACHILD  AS EXTRACHILD, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME AS BOOKEDBY, HOTELBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, HOTELBOOKINGMASTER.BOOKING_BOOKTYPE AS TYPE, HOTELBOOKINGMASTER.BOOKING_CMPID AS CMPID, HOTELBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOTELBOOKINGMASTER.BOOKING_YEARID AS YEARID FROM HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID INNER JOIN LEDGERS ON HOTELBOOKINGMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOTELBOOKINGMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOTELBOOKINGMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN HOTELBOOKINGMASTER_DESC ON HOTELBOOKINGMASTER.BOOKING_NO = HOTELBOOKINGMASTER_DESC.BOOKING_NO AND HOTELBOOKINGMASTER.BOOKING_BOOKTYPE = HOTELBOOKINGMASTER_DESC.BOOKING_BOOKTYPE AND HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELBOOKINGMASTER_DESC.BOOKING_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELBOOKINGMASTER_DESC.BOOKING_YEARID INNER JOIN PLANMASTER ON HOTELBOOKINGMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOTELBOOKINGMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOTELBOOKINGMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOTELBOOKINGMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOTELBOOKINGMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOTELBOOKINGMASTER.BOOKING_SALERETURN = 0) AND (HOTELBOOKINGMASTER.BOOKING_AMD_DONE = 0) UNION ALL SELECT CAST(0 AS BIT) AS CHK, HOLIDAYPACKAGEMASTER.BOOKING_NO AS SRNO, HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS, HOLIDAYPACKAGEMASTER.BOOKING_REFNO, HOLIDAYPACKAGEMASTER.BOOKING_DATE, GUESTMASTER.GUEST_NAME, LEDGERS.Acc_cmpname AS NAME, HOTELMASTER.HOTEL_NAME, ISNULL(CITYMASTER.city_name, '') AS CITY, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE, PLANMASTER.PLAN_NAME AS MEALPLAN, HOLIDAYPACKAGEMASTER_DESC.BOOKING_NOOFROOMS AS TOTALROOMS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRAADULTS AS EXTRAADULTS, HOLIDAYPACKAGEMASTER_DESC.BOOKING_EXTRACHILDS  AS EXTRACHILD, HOLIDAYPACKAGEMASTER.BOOKING_PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME, HOLIDAYPACKAGEMASTER.BOOKING_SALEBALANCE, 'HOLIDAYPACKAGE' AS TYPE, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID FROM GUESTMASTER INNER JOIN HOLIDAYPACKAGEMASTER_GUESTDETAILS ON GUESTMASTER.GUEST_ID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_GUESTID AND GUESTMASTER.GUEST_CMPID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID AND GUESTMASTER.GUEST_LOCATIONID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID AND GUESTMASTER.GUEST_YEARID = HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID INNER JOIN HOLIDAYPACKAGEMASTER_DESC INNER JOIN HOLIDAYPACKAGEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO = HOLIDAYPACKAGEMASTER.BOOKING_NO AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOLIDAYPACKAGEMASTER.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOLIDAYPACKAGEMASTER.BOOKING_YEARID INNER JOIN BOOKEDBYMASTER ON HOLIDAYPACKAGEMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID AND HOLIDAYPACKAGEMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID ON HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_NO = HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_CMPID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_GUESTDETAILS.BOOKING_YEARID = HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID INNER JOIN LEDGERS ON HOLIDAYPACKAGEMASTER.BOOKING_LEDGERID = LEDGERS.Acc_id AND HOLIDAYPACKAGEMASTER.BOOKING_CMPID = LEDGERS.Acc_cmpid AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = LEDGERS.Acc_locationid AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = LEDGERS.Acc_yearid INNER JOIN PLANMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_PLANID = PLANMASTER.PLAN_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = PLANMASTER.PLAN_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = PLANMASTER.PLAN_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = PLANMASTER.PLAN_YEARID LEFT OUTER JOIN CITYMASTER ON HOTELMASTER.HOTEL_YEARID = CITYMASTER.city_yearid AND HOTELMASTER.HOTEL_LOCATIONID = CITYMASTER.city_locationid AND HotelMaster.HOTEL_CMPID = citymaster.city_cmpid And HotelMaster.HOTEL_CITYID = citymaster.city_id WHERE (HOLIDAYPACKAGEMASTER.BOOKING_CANCELLED = 'FALSE') AND (HOLIDAYPACKAGEMASTER.BOOKING_AMD_DONE = 0) AND (HOLIDAYPACKAGEMASTER.BOOKING_SALERETURN = 0)) AS T ", WHERECLAUSE & " AND T.CMPID =" & CmpId & " AND T.LOCATIONID = " & Locationid & " AND T.YEARID = " & YearId & " ORDER BY T.SRNO")
            Else
                'dt = objclsCMST.search("*", "", " (SELECT CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS SRNO, HOTELBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS [DATE], GUESTMASTER.GUEST_NAME AS GUESTNAME , HOTELMASTER.HOTEL_NAME AS HOTELNAME,  HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME aS BOOKEDBY, BOOKING_SALEBALANCE AS BALANCE, BOOKING_BOOKTYPE AS TYPE , BOOKING_CMPID AS CMPID, BOOKING_LOCATIONID AS LOCATIONID, BOOKING_YEARID AS YEARID, '' AS NAME, '' AS PLACE, '' AS MEALPLAN, 0 AS TOTALROOMS, 0 AS EXTRAADULTS FROM HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID WHERE BOOKING_CANCELLED = 'FALSE' AND BOOKING_SALERETURN = 0  AND BOOKING_AMD_DONE = 0  UNION ALL SELECT   CAST (0 AS BIT) AS CHK, HOLIDAYPACKAGEMASTER.BOOKING_NO AS SRNO, HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS, HOLIDAYPACKAGEMASTER.BOOKING_REFNO, HOLIDAYPACKAGEMASTER.BOOKING_DATE, HOLIDAYPACKAGEMASTER.BOOKING_TOURNAME, HOTELMASTER.HOTEL_NAME, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE, HOLIDAYPACKAGEMASTER.BOOKING_PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME, HOLIDAYPACKAGEMASTER.BOOKING_SALEBALANCE, 'HOLIDAYPACKAGE' AS TYPE, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID, '' AS NAME, '' AS PLACE, '' AS MEALPLAN, 0 AS TOTALROOMS, 0 AS EXTRAADULTS FROM HOLIDAYPACKAGEMASTER_DESC INNER JOIN HOLIDAYPACKAGEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO = HOLIDAYPACKAGEMASTER.BOOKING_NO AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOLIDAYPACKAGEMASTER.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOLIDAYPACKAGEMASTER.BOOKING_YEARID INNER JOIN BOOKEDBYMASTER ON HOLIDAYPACKAGEMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID AND HOLIDAYPACKAGEMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HotelMaster.HOTEL_YEARID WHERE HOLIDAYPACKAGEMASTER.BOOKING_CANCELLED= 'FALSE' AND HOLIDAYPACKAGEMASTER.BOOKING_AMD_DONE = 0 AND HOLIDAYPACKAGEMASTER.BOOKING_SALERETURN = 0) AS T ", WHERECLAUSE & " AND T.CMPID =" & CmpId & " ORDER BY T.SRNO")
                dt = objclsCMST.search("*", "", " (SELECT CAST(0 AS BIT) AS CHK, HOTELBOOKINGMASTER.BOOKING_NO AS SRNO, HOTELBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, HOTELBOOKINGMASTER.BOOKING_REFNO AS REFNO, HOTELBOOKINGMASTER.BOOKING_DATE AS [DATE], GUESTMASTER.GUEST_NAME AS GUESTNAME , HOTELMASTER.HOTEL_NAME AS HOTELNAME,  HOTELBOOKINGMASTER.BOOKING_ARRIVAL AS ARRIVAL, HOTELBOOKINGMASTER.BOOKING_DEPARTURE AS DEPARTURE, HOTELBOOKINGMASTER.BOOKING_PICKUPDETAILS AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME aS BOOKEDBY, BOOKING_SALEBALANCE AS BALANCE, BOOKING_BOOKTYPE AS TYPE , BOOKING_CMPID AS CMPID, BOOKING_LOCATIONID AS LOCATIONID, BOOKING_YEARID AS YEARID, '' AS NAME, '' AS PLACE, '' AS MEALPLAN, 0 AS TOTALROOMS, 0 AS EXTRAADULTS, BOOKING_SALEREGISTERID AS SALEREGID FROM HOTELBOOKINGMASTER INNER JOIN GUESTMASTER ON HOTELBOOKINGMASTER.BOOKING_GUESTID = GUESTMASTER.GUEST_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = GUESTMASTER.GUEST_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = GUESTMASTER.GUEST_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = GUESTMASTER.GUEST_YEARID INNER JOIN HOTELMASTER ON HOTELBOOKINGMASTER.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = HOTELMASTER.HOTEL_YEARID AND HOTELBOOKINGMASTER.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID INNER JOIN BOOKEDBYMASTER ON HOTELBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID AND HOTELBOOKINGMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOTELBOOKINGMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOTELBOOKINGMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID WHERE BOOKING_CANCELLED = 'FALSE' AND BOOKING_SALERETURN = 0  AND BOOKING_AMD_DONE = 0  UNION ALL SELECT   CAST (0 AS BIT) AS CHK, HOLIDAYPACKAGEMASTER.BOOKING_NO AS SRNO, HOLIDAYPACKAGEMASTER.BOOKING_SALEBILLINITIALS, HOLIDAYPACKAGEMASTER.BOOKING_REFNO, HOLIDAYPACKAGEMASTER.BOOKING_DATE, HOLIDAYPACKAGEMASTER.BOOKING_TOURNAME, HOTELMASTER.HOTEL_NAME, HOLIDAYPACKAGEMASTER_DESC.BOOKING_ARRIVALDATE, HOLIDAYPACKAGEMASTER_DESC.BOOKING_DEPARTUREDATE, HOLIDAYPACKAGEMASTER.BOOKING_PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME, HOLIDAYPACKAGEMASTER.BOOKING_SALEBALANCE, 'HOLIDAYPACKAGE' AS TYPE, HOLIDAYPACKAGEMASTER.BOOKING_CMPID AS CMPID, HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AS LOCATIONID, HOLIDAYPACKAGEMASTER.BOOKING_YEARID AS YEARID, '' AS NAME, '' AS PLACE, '' AS MEALPLAN, 0 AS TOTALROOMS, 0 AS EXTRAADULTS, BOOKING_SALEREGISTERID AS SALEREGID FROM HOLIDAYPACKAGEMASTER_DESC INNER JOIN HOLIDAYPACKAGEMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_NO = HOLIDAYPACKAGEMASTER.BOOKING_NO AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOLIDAYPACKAGEMASTER.BOOKING_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HOLIDAYPACKAGEMASTER.BOOKING_YEARID INNER JOIN BOOKEDBYMASTER ON HOLIDAYPACKAGEMASTER.BOOKING_CMPID = BOOKEDBYMASTER.BOOKEDBY_CMPID AND HOLIDAYPACKAGEMASTER.BOOKING_LOCATIONID = BOOKEDBYMASTER.BOOKEDBY_LOCATIONID AND HOLIDAYPACKAGEMASTER.BOOKING_YEARID = BOOKEDBYMASTER.BOOKEDBY_YEARID AND HOLIDAYPACKAGEMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN HOTELMASTER ON HOLIDAYPACKAGEMASTER_DESC.BOOKING_HOTELID = HOTELMASTER.HOTEL_ID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_CMPID = HOTELMASTER.HOTEL_CMPID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_LOCATIONID = HOTELMASTER.HOTEL_LOCATIONID AND HOLIDAYPACKAGEMASTER_DESC.BOOKING_YEARID = HotelMaster.HOTEL_YEARID WHERE HOLIDAYPACKAGEMASTER.BOOKING_CANCELLED= 'FALSE' AND HOLIDAYPACKAGEMASTER.BOOKING_AMD_DONE = 0 AND HOLIDAYPACKAGEMASTER.BOOKING_SALERETURN = 0 UNION ALL SELECT CAST (0 AS BIT) AS CHK, AIRLINEBOOKINGMASTER.BOOKING_NO AS SRNO, AIRLINEBOOKINGMASTER.BOOKING_SALEBILLINITIALS AS BOOKINGNO, AIRLINEBOOKINGMASTER.BOOKING_REFNO AS REFNO, AIRLINEBOOKINGMASTER.BOOKING_DATE AS DATE, AIRLINEPASSDETAILS_LEDGER.PASSNAME AS GUESTNAME, '' AS HOTELNAME, AIRLINEBOOKINGMASTER.BOOKING_TICKETDATE AS ARRIVAL, AIRLINEBOOKINGMASTER.BOOKING_TICKETDATE AS DEPARTURE, AIRLINEPASSDETAILS_LEDGER.SECTOR AS PICKUPDETAILS, BOOKEDBYMASTER.BOOKEDBY_NAME AS BOOKEDBY, AIRLINEBOOKINGMASTER.BOOKING_SALEBALANCE AS BALANCE, 'AIRLINEBOOKING' AS TYPE, AIRLINEBOOKINGMASTER.BOOKING_CMPID AS CMPID, AIRLINEBOOKINGMASTER.BOOKING_LOCATIONID AS LOCATIONID, AIRLINEBOOKINGMASTER.BOOKING_YEARID AS YEARID,'' AS NAME,'' AS PLACE,'' AS MEALPLAN,0 AS TOTALROOMS,0 AS EXTRAADULTS, BOOKING_SALEREGISTERID AS SALEREGID FROM AIRLINEBOOKINGMASTER INNER JOIN BOOKEDBYMASTER ON AIRLINEBOOKINGMASTER.BOOKING_BOOKEDBYID = BOOKEDBYMASTER.BOOKEDBY_ID INNER JOIN AIRLINEPASSDETAILS_LEDGER ON AIRLINEBOOKINGMASTER.BOOKING_YEARID = AIRLINEPASSDETAILS_LEDGER.YEARID AND AIRLINEBOOKINGMASTER.BOOKING_NO = AIRLINEPASSDETAILS_LEDGER.BOOKINGNO AND AIRLINEBOOKINGMASTER.BOOKING_SALEREGISTERID = AIRLINEPASSDETAILS_LEDGER.REGID WHERE AIRLINEBOOKINGMASTER.BOOKING_CANCELLED= 'FALSE' AND AIRLINEBOOKINGMASTER.BOOKING_DONE = 0 AND AIRLINEBOOKINGMASTER.BOOKING_SALERETURN = 0) AS T ", WHERECLAUSE & " AND T.CMPID =" & CmpId & " ORDER BY T.SRNO")

                gridbill.Columns("NAME").Visible = False
                gridbill.Columns("CITY").Visible = False
                gridbill.Columns("MEALPLAN").Visible = False
                gridbill.Columns("TOTALROOMS").Visible = False
                gridbill.Columns("EXTRAADULTS").Visible = False
                gridbill.Columns("EXTRACHILD").Visible = False
            End If

            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub showform(ByVal editval As Boolean, ByVal BOOKINGNO As Integer, ByVal TYPE As String, Optional ByVal SALEREGID As Integer = 0)
        Try
            If (editval = False) Or (editval = True And gridbill.RowCount > 0) Then
                If TYPE = "HOLIDAYPACKAGE" Then
                    Dim OBJBOOKING As New HolidayPackage
                    OBJBOOKING.MdiParent = MDIMain
                    OBJBOOKING.edit = editval
                    OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                    OBJBOOKING.Show()
                ElseIf TYPE = "BOOKING" Then
                    Dim OBJBOOKING As New HotelBookings
                    OBJBOOKING.MdiParent = MDIMain
                    OBJBOOKING.FRMSTRING = TYPE
                    OBJBOOKING.edit = editval
                    OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                    OBJBOOKING.Show()
                Else

                    'Dim OBJBOOKING As New AirlineBookings
                    'OBJBOOKING.MdiParent = MDIMain
                    'OBJBOOKING.FRMSTRING = TYPE
                    'OBJBOOKING.SALEregid = SALEREGID
                    'OBJBOOKING.edit = editval
                    'OBJBOOKING.TEMPBOOKINGNO = BOOKINGNO
                    'OBJBOOKING.Show()
                End If

            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub CMDOK_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDOK.Click
        Try
            showform(True, gridbill.GetFocusedRowCellValue("SRNO"), gridbill.GetFocusedRowCellValue("TYPE"), gridbill.GetFocusedRowCellValue("SALEREGID"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles gridbill.DoubleClick
        Try
            showform(True, gridbill.GetFocusedRowCellValue("SRNO"), gridbill.GetFocusedRowCellValue("TYPE"), gridbill.GetFocusedRowCellValue("SALEREGID"))
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CheckInList_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdshowdetails_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdshowdetails.Click
        Try
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDPRINT_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDPRINT.Click
        Try
            Dim PATH As String = "" = ""
            If FileIO.FileSystem.FileExists(PATH) = True Then FileIO.FileSystem.DeleteFile(PATH)
            PATH = Application.StartupPath & "\Ckeck In List.XLS"

            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True

            Dim workbook As String = PATH
            If FileIO.FileSystem.FileExists(PATH) = True Then Interaction.GetObject(workbook).close(False)
            GC.Collect()
            'For Each proc In System.Diagnostics.Process.GetProcessesByName("Excel")
            '    proc.Kill()
            'Next

            Dim PERIOD As String = ""
            If chkdate.CheckState = CheckState.Unchecked Then
                PERIOD = DateAdd(DateInterval.Day, 1, Now.Date) & " - " & DateAdd(DateInterval.Day, 1, Now.Date)
            Else
                PERIOD = dtfrom.Value.Date & " - " & dtto.Value.Date
            End If

            opti.SheetName = "Ckeck In List"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Ckeck In List", gridbill.VisibleColumns.Count + gridbill.GroupCount, "", PERIOD)

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub getFromToDate()
       
        a1 = DatePart(DateInterval.Day, dtfrom.Value.Date)
        a2 = DatePart(DateInterval.Month, dtfrom.Value.Date)
        a3 = DatePart(DateInterval.Year, dtfrom.Value.Date)
        fromD = "(" & a3 & "," & a2 & "," & a1 & ")"

        a11 = DatePart(DateInterval.Day, dtto.Value.Date)
        a12 = DatePart(DateInterval.Month, dtto.Value.Date)
        a13 = DatePart(DateInterval.Year, dtto.Value.Date)
        toD = "(" & a13 & "," & a12 & "," & a11 & ")"
    End Sub

    Private Sub CMDMAIL_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDMAIL.Click
        Try

            Dim SEARCH As String = ""
            Dim HOTEL As String = ""
            For i As Integer = 0 To gridbill.RowCount - 1
                Dim dtrow As DataRow = gridbill.GetDataRow(i)
                If Convert.ToBoolean(dtrow("CHK")) = True Then
                    If SEARCH = "" Then
                        SEARCH = " AND ({CHECKINLIST.BOOKINGNO} = '" & dtrow("BOOKINGNO") & "'"
                    Else
                        SEARCH = SEARCH & " OR {CHECKINLIST.BOOKINGNO}  = '" & dtrow("BOOKINGNO") & "'"
                    End If
                    If HOTEL = "" Then
                        HOTEL = " AND ({CHECKINLIST.HOTELNAME} = '" & dtrow("HOTELNAME") & "'"
                    Else
                        HOTEL = HOTEL & " OR {CHECKINLIST.HOTELNAME}  = '" & dtrow("HOTELNAME") & "'"
                    End If
                End If
            Next
            If SEARCH <> "" Then SEARCH = SEARCH & ")"
            If HOTEL <> "" Then HOTEL = HOTEL & ")"

            SEARCH = SEARCH & HOTEL

            
            Dim OBJCHECK As New OtherReportsDesign
            OBJCHECK.MdiParent = MDIMain
            OBJCHECK.SEARCH = SEARCH
            OBJCHECK.FRMSTRING = "CHECKIN"
            OBJCHECK.Show()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class